#define SDL_MAIN_HANDLED
#include <SDL3/SDL.h>

/* SDL's window flags are macros whose bodies expand through SDL_UINT64_C(),
 * which bindgen's macro evaluator cannot fold: it only ever sees the raw token
 * sequence `SDL_UINT64_C ( 0x... )` and silently drops the constant.
 * Re-declaring them lets clang compute the values instead.
 *
 * The `##` suppresses expansion of the argument, so the identifier is literally
 * karna_SDL_WINDOW_FULLSCREEN; the initializer has no adjacent `##` and does
 * expand. The prefix is required - a same-named declaration would expand on
 * both sides and fail to parse. regenerate.rs strips it back off. */
#define KARNA_WINDOW_FLAG(name) static const SDL_WindowFlags karna_##name = name;

KARNA_WINDOW_FLAG(SDL_WINDOW_FULLSCREEN)
KARNA_WINDOW_FLAG(SDL_WINDOW_OPENGL)
KARNA_WINDOW_FLAG(SDL_WINDOW_OCCLUDED)
KARNA_WINDOW_FLAG(SDL_WINDOW_HIDDEN)
KARNA_WINDOW_FLAG(SDL_WINDOW_BORDERLESS)
KARNA_WINDOW_FLAG(SDL_WINDOW_RESIZABLE)
KARNA_WINDOW_FLAG(SDL_WINDOW_MINIMIZED)
KARNA_WINDOW_FLAG(SDL_WINDOW_MAXIMIZED)
KARNA_WINDOW_FLAG(SDL_WINDOW_MOUSE_GRABBED)
KARNA_WINDOW_FLAG(SDL_WINDOW_INPUT_FOCUS)
KARNA_WINDOW_FLAG(SDL_WINDOW_MOUSE_FOCUS)
KARNA_WINDOW_FLAG(SDL_WINDOW_EXTERNAL)
KARNA_WINDOW_FLAG(SDL_WINDOW_MODAL)
KARNA_WINDOW_FLAG(SDL_WINDOW_HIGH_PIXEL_DENSITY)
KARNA_WINDOW_FLAG(SDL_WINDOW_MOUSE_CAPTURE)
KARNA_WINDOW_FLAG(SDL_WINDOW_MOUSE_RELATIVE_MODE)
KARNA_WINDOW_FLAG(SDL_WINDOW_ALWAYS_ON_TOP)
KARNA_WINDOW_FLAG(SDL_WINDOW_UTILITY)
KARNA_WINDOW_FLAG(SDL_WINDOW_TOOLTIP)
KARNA_WINDOW_FLAG(SDL_WINDOW_POPUP_MENU)
KARNA_WINDOW_FLAG(SDL_WINDOW_KEYBOARD_GRABBED)
KARNA_WINDOW_FLAG(SDL_WINDOW_FILL_DOCUMENT)
KARNA_WINDOW_FLAG(SDL_WINDOW_VULKAN)
KARNA_WINDOW_FLAG(SDL_WINDOW_METAL)
KARNA_WINDOW_FLAG(SDL_WINDOW_TRANSPARENT)
KARNA_WINDOW_FLAG(SDL_WINDOW_NOT_FOCUSABLE)
