/* automatically generated by rust-bindgen 0.72.1 */

pub const JS_PROP_CONFIGURABLE: u32 = 1;
pub const JS_PROP_WRITABLE: u32 = 2;
pub const JS_PROP_ENUMERABLE: u32 = 4;
pub const JS_PROP_C_W_E: u32 = 7;
pub const JS_PROP_LENGTH: u32 = 8;
pub const JS_PROP_TMASK: u32 = 48;
pub const JS_PROP_NORMAL: u32 = 0;
pub const JS_PROP_GETSET: u32 = 16;
pub const JS_PROP_VARREF: u32 = 32;
pub const JS_PROP_AUTOINIT: u32 = 48;
pub const JS_PROP_HAS_SHIFT: u32 = 8;
pub const JS_PROP_HAS_CONFIGURABLE: u32 = 256;
pub const JS_PROP_HAS_WRITABLE: u32 = 512;
pub const JS_PROP_HAS_ENUMERABLE: u32 = 1024;
pub const JS_PROP_HAS_GET: u32 = 2048;
pub const JS_PROP_HAS_SET: u32 = 4096;
pub const JS_PROP_HAS_VALUE: u32 = 8192;
pub const JS_PROP_THROW: u32 = 16384;
pub const JS_PROP_THROW_STRICT: u32 = 32768;
pub const JS_PROP_NO_ADD: u32 = 65536;
pub const JS_PROP_NO_EXOTIC: u32 = 131072;
pub const JS_PROP_DEFINE_PROPERTY: u32 = 262144;
pub const JS_PROP_REFLECT_DEFINE_PROPERTY: u32 = 524288;
pub const JS_DEFAULT_STACK_SIZE: u32 = 1048576;
pub const JS_EVAL_TYPE_GLOBAL: u32 = 0;
pub const JS_EVAL_TYPE_MODULE: u32 = 1;
pub const JS_EVAL_TYPE_DIRECT: u32 = 2;
pub const JS_EVAL_TYPE_INDIRECT: u32 = 3;
pub const JS_EVAL_TYPE_MASK: u32 = 3;
pub const JS_EVAL_FLAG_STRICT: u32 = 8;
pub const JS_EVAL_FLAG_UNUSED: u32 = 16;
pub const JS_EVAL_FLAG_COMPILE_ONLY: u32 = 32;
pub const JS_EVAL_FLAG_BACKTRACE_BARRIER: u32 = 64;
pub const JS_EVAL_FLAG_ASYNC: u32 = 128;
pub const JS_DUMP_BYTECODE_FINAL: u32 = 1;
pub const JS_DUMP_BYTECODE_PASS2: u32 = 2;
pub const JS_DUMP_BYTECODE_PASS1: u32 = 4;
pub const JS_DUMP_BYTECODE_HEX: u32 = 16;
pub const JS_DUMP_BYTECODE_PC2LINE: u32 = 32;
pub const JS_DUMP_BYTECODE_STACK: u32 = 64;
pub const JS_DUMP_BYTECODE_STEP: u32 = 128;
pub const JS_DUMP_READ_OBJECT: u32 = 256;
pub const JS_DUMP_FREE: u32 = 512;
pub const JS_DUMP_GC: u32 = 1024;
pub const JS_DUMP_GC_FREE: u32 = 2048;
pub const JS_DUMP_MODULE_RESOLVE: u32 = 4096;
pub const JS_DUMP_PROMISE: u32 = 8192;
pub const JS_DUMP_LEAKS: u32 = 16384;
pub const JS_DUMP_ATOM_LEAKS: u32 = 32768;
pub const JS_DUMP_MEM: u32 = 65536;
pub const JS_DUMP_OBJECTS: u32 = 131072;
pub const JS_DUMP_ATOMS: u32 = 262144;
pub const JS_DUMP_SHAPES: u32 = 524288;
pub const JS_ABORT_ON_LEAKS: u32 = 1097728;
pub const JS_ATOM_NULL: u32 = 0;
pub const JS_CALL_FLAG_CONSTRUCTOR: u32 = 1;
pub const JS_EVAL_OPTIONS_VERSION: u32 = 1;
pub const JS_INVALID_CLASS_ID: u32 = 0;
pub const JS_GPN_STRING_MASK: u32 = 1;
pub const JS_GPN_SYMBOL_MASK: u32 = 2;
pub const JS_GPN_PRIVATE_MASK: u32 = 4;
pub const JS_GPN_ENUM_ONLY: u32 = 16;
pub const JS_GPN_SET_ENUM: u32 = 32;
pub const JS_WRITE_OBJ_BYTECODE: u32 = 1;
pub const JS_WRITE_OBJ_BSWAP: u32 = 0;
pub const JS_WRITE_OBJ_SAB: u32 = 4;
pub const JS_WRITE_OBJ_REFERENCE: u32 = 8;
pub const JS_WRITE_OBJ_STRIP_SOURCE: u32 = 16;
pub const JS_WRITE_OBJ_STRIP_DEBUG: u32 = 32;
pub const JS_READ_OBJ_BYTECODE: u32 = 1;
pub const JS_READ_OBJ_ROM_DATA: u32 = 0;
pub const JS_READ_OBJ_SAB: u32 = 4;
pub const JS_READ_OBJ_REFERENCE: u32 = 8;
pub const JS_DEF_CFUNC: u32 = 0;
pub const JS_DEF_CGETSET: u32 = 1;
pub const JS_DEF_CGETSET_MAGIC: u32 = 2;
pub const JS_DEF_PROP_STRING: u32 = 3;
pub const JS_DEF_PROP_INT32: u32 = 4;
pub const JS_DEF_PROP_INT64: u32 = 5;
pub const JS_DEF_PROP_DOUBLE: u32 = 6;
pub const JS_DEF_PROP_UNDEFINED: u32 = 7;
pub const JS_DEF_OBJECT: u32 = 8;
pub const JS_DEF_ALIAS: u32 = 9;
pub const JS_DEF_PROP_SYMBOL: u32 = 10;
pub const JS_DEF_PROP_BOOL: u32 = 11;
pub const QJS_VERSION_MAJOR: u32 = 0;
pub const QJS_VERSION_MINOR: u32 = 17;
pub const QJS_VERSION_PATCH: u32 = 0;
pub const QJS_VERSION_SUFFIX: &[u8; 1] = b"\0";
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSRuntime {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSContext {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSObject {
    _unused: [u8; 0],
}
pub type JSClassID = u32;
pub type JSAtom = u32;
pub const JS_TAG_FIRST: _bindgen_ty_2 = -9;
pub const JS_TAG_BIG_INT: _bindgen_ty_2 = -9;
pub const JS_TAG_SYMBOL: _bindgen_ty_2 = -8;
pub const JS_TAG_STRING: _bindgen_ty_2 = -7;
pub const JS_TAG_STRING_ROPE: _bindgen_ty_2 = -6;
pub const JS_TAG_MODULE: _bindgen_ty_2 = -3;
pub const JS_TAG_FUNCTION_BYTECODE: _bindgen_ty_2 = -2;
pub const JS_TAG_OBJECT: _bindgen_ty_2 = -1;
pub const JS_TAG_INT: _bindgen_ty_2 = 0;
pub const JS_TAG_BOOL: _bindgen_ty_2 = 1;
pub const JS_TAG_NULL: _bindgen_ty_2 = 2;
pub const JS_TAG_UNDEFINED: _bindgen_ty_2 = 3;
pub const JS_TAG_UNINITIALIZED: _bindgen_ty_2 = 4;
pub const JS_TAG_CATCH_OFFSET: _bindgen_ty_2 = 5;
pub const JS_TAG_EXCEPTION: _bindgen_ty_2 = 6;
pub const JS_TAG_SHORT_BIG_INT: _bindgen_ty_2 = 7;
pub const JS_TAG_FLOAT64: _bindgen_ty_2 = 8;
pub type _bindgen_ty_2 = core::ffi::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union JSValueUnion {
    pub int32: i32,
    pub float64: f64,
    pub ptr: *mut core::ffi::c_void,
    pub short_big_int: i32,
}
impl Default for JSValueUnion {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct JSValue {
    pub u: JSValueUnion,
    pub tag: i64,
}
impl Default for JSValue {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    #[link_name = "JS_VALUE_IS_NAN__extern"]
    pub fn JS_VALUE_IS_NAN(v: JSValue) -> bool;
}
pub type JSCFunction = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        this_val: JSValue,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
    ) -> JSValue,
>;
pub type JSCFunctionMagic = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        this_val: JSValue,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
        magic: core::ffi::c_int,
    ) -> JSValue,
>;
pub type JSCFunctionData = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        this_val: JSValue,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
        magic: core::ffi::c_int,
        func_data: *mut JSValue,
    ) -> JSValue,
>;
pub type JSCClosure = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        this_val: JSValue,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
        magic: core::ffi::c_int,
        opaque: *mut core::ffi::c_void,
    ) -> JSValue,
>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct JSMallocFunctions {
    pub js_calloc: ::core::option::Option<
        unsafe extern "C" fn(
            opaque: *mut core::ffi::c_void,
            count: usize,
            size: usize,
        ) -> *mut core::ffi::c_void,
    >,
    pub js_malloc: ::core::option::Option<
        unsafe extern "C" fn(opaque: *mut core::ffi::c_void, size: usize) -> *mut core::ffi::c_void,
    >,
    pub js_free: ::core::option::Option<
        unsafe extern "C" fn(opaque: *mut core::ffi::c_void, ptr: *mut core::ffi::c_void),
    >,
    pub js_realloc: ::core::option::Option<
        unsafe extern "C" fn(
            opaque: *mut core::ffi::c_void,
            ptr: *mut core::ffi::c_void,
            size: usize,
        ) -> *mut core::ffi::c_void,
    >,
    pub js_malloc_usable_size:
        ::core::option::Option<unsafe extern "C" fn(ptr: *const core::ffi::c_void) -> usize>,
}
pub type JSRuntimeFinalizer =
    ::core::option::Option<unsafe extern "C" fn(rt: *mut JSRuntime, arg: *mut core::ffi::c_void)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSGCObjectHeader {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn JS_NewRuntime() -> *mut JSRuntime;
}
unsafe extern "C" {
    pub fn JS_SetRuntimeInfo(rt: *mut JSRuntime, info: *const core::ffi::c_char);
}
unsafe extern "C" {
    pub fn JS_SetMemoryLimit(rt: *mut JSRuntime, limit: usize);
}
unsafe extern "C" {
    pub fn JS_SetDumpFlags(rt: *mut JSRuntime, flags: u64);
}
unsafe extern "C" {
    pub fn JS_GetDumpFlags(rt: *mut JSRuntime) -> u64;
}
unsafe extern "C" {
    pub fn JS_GetGCThreshold(rt: *mut JSRuntime) -> usize;
}
unsafe extern "C" {
    pub fn JS_SetGCThreshold(rt: *mut JSRuntime, gc_threshold: usize);
}
unsafe extern "C" {
    pub fn JS_SetMaxStackSize(rt: *mut JSRuntime, stack_size: usize);
}
unsafe extern "C" {
    pub fn JS_UpdateStackTop(rt: *mut JSRuntime);
}
unsafe extern "C" {
    pub fn JS_NewRuntime2(
        mf: *const JSMallocFunctions,
        opaque: *mut core::ffi::c_void,
    ) -> *mut JSRuntime;
}
unsafe extern "C" {
    pub fn JS_FreeRuntime(rt: *mut JSRuntime);
}
unsafe extern "C" {
    pub fn JS_GetRuntimeOpaque(rt: *mut JSRuntime) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn JS_SetRuntimeOpaque(rt: *mut JSRuntime, opaque: *mut core::ffi::c_void);
}
unsafe extern "C" {
    pub fn JS_AddRuntimeFinalizer(
        rt: *mut JSRuntime,
        finalizer: JSRuntimeFinalizer,
        arg: *mut core::ffi::c_void,
    ) -> core::ffi::c_int;
}
pub type JS_MarkFunc =
    ::core::option::Option<unsafe extern "C" fn(rt: *mut JSRuntime, gp: *mut JSGCObjectHeader)>;
unsafe extern "C" {
    pub fn JS_MarkValue(rt: *mut JSRuntime, val: JSValue, mark_func: JS_MarkFunc);
}
unsafe extern "C" {
    pub fn JS_RunGC(rt: *mut JSRuntime);
}
unsafe extern "C" {
    pub fn JS_IsLiveObject(rt: *mut JSRuntime, obj: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_NewContext(rt: *mut JSRuntime) -> *mut JSContext;
}
unsafe extern "C" {
    pub fn JS_FreeContext(s: *mut JSContext);
}
unsafe extern "C" {
    pub fn JS_DupContext(ctx: *mut JSContext) -> *mut JSContext;
}
unsafe extern "C" {
    pub fn JS_GetContextOpaque(ctx: *mut JSContext) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn JS_SetContextOpaque(ctx: *mut JSContext, opaque: *mut core::ffi::c_void);
}
unsafe extern "C" {
    pub fn JS_GetRuntime(ctx: *mut JSContext) -> *mut JSRuntime;
}
unsafe extern "C" {
    pub fn JS_SetClassProto(ctx: *mut JSContext, class_id: JSClassID, obj: JSValue);
}
unsafe extern "C" {
    pub fn JS_GetClassProto(ctx: *mut JSContext, class_id: JSClassID) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetFunctionProto(ctx: *mut JSContext) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewContextRaw(rt: *mut JSRuntime) -> *mut JSContext;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicBaseObjects(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicDate(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicEval(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicRegExpCompiler(ctx: *mut JSContext);
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicRegExp(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicJSON(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicProxy(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicMapSet(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicTypedArrays(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicPromise(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicBigInt(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicWeakRef(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddPerformance(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicDOMException(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddIntrinsicAToB(ctx: *mut JSContext) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_IsEqual(ctx: *mut JSContext, op1: JSValue, op2: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_IsStrictEqual(ctx: *mut JSContext, op1: JSValue, op2: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsSameValue(ctx: *mut JSContext, op1: JSValue, op2: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsSameValueZero(ctx: *mut JSContext, op1: JSValue, op2: JSValue) -> bool;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct JSMemoryUsage {
    pub malloc_size: i64,
    pub malloc_limit: i64,
    pub memory_used_size: i64,
    pub malloc_count: i64,
    pub memory_used_count: i64,
    pub atom_count: i64,
    pub atom_size: i64,
    pub str_count: i64,
    pub str_size: i64,
    pub obj_count: i64,
    pub obj_size: i64,
    pub prop_count: i64,
    pub prop_size: i64,
    pub shape_count: i64,
    pub shape_size: i64,
    pub js_func_count: i64,
    pub js_func_size: i64,
    pub js_func_code_size: i64,
    pub js_func_pc2line_count: i64,
    pub js_func_pc2line_size: i64,
    pub c_func_count: i64,
    pub array_count: i64,
    pub fast_array_count: i64,
    pub fast_array_elements: i64,
    pub binary_object_count: i64,
    pub binary_object_size: i64,
}
unsafe extern "C" {
    pub fn JS_ComputeMemoryUsage(rt: *mut JSRuntime, s: *mut JSMemoryUsage);
}
unsafe extern "C" {
    pub fn JS_DumpMemoryUsage(fp: *mut FILE, s: *const JSMemoryUsage, rt: *mut JSRuntime);
}
unsafe extern "C" {
    pub fn JS_NewAtomLen(ctx: *mut JSContext, str_: *const core::ffi::c_char, len: usize)
        -> JSAtom;
}
unsafe extern "C" {
    pub fn JS_NewAtom(ctx: *mut JSContext, str_: *const core::ffi::c_char) -> JSAtom;
}
unsafe extern "C" {
    pub fn JS_NewAtomUInt32(ctx: *mut JSContext, n: u32) -> JSAtom;
}
unsafe extern "C" {
    pub fn JS_DupAtom(ctx: *mut JSContext, v: JSAtom) -> JSAtom;
}
unsafe extern "C" {
    pub fn JS_DupAtomRT(rt: *mut JSRuntime, v: JSAtom) -> JSAtom;
}
unsafe extern "C" {
    pub fn JS_FreeAtom(ctx: *mut JSContext, v: JSAtom);
}
unsafe extern "C" {
    pub fn JS_FreeAtomRT(rt: *mut JSRuntime, v: JSAtom);
}
unsafe extern "C" {
    pub fn JS_AtomToValue(ctx: *mut JSContext, atom: JSAtom) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_AtomToString(ctx: *mut JSContext, atom: JSAtom) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_AtomToCStringLen(
        ctx: *mut JSContext,
        plen: *mut usize,
        atom: JSAtom,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    #[link_name = "JS_AtomToCString__extern"]
    pub fn JS_AtomToCString(ctx: *mut JSContext, atom: JSAtom) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn JS_ValueToAtom(ctx: *mut JSContext, val: JSValue) -> JSAtom;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct JSPropertyEnum {
    pub is_enumerable: bool,
    pub atom: JSAtom,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct JSPropertyDescriptor {
    pub flags: core::ffi::c_int,
    pub value: JSValue,
    pub getter: JSValue,
    pub setter: JSValue,
}
impl Default for JSPropertyDescriptor {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct JSClassExoticMethods {
    pub get_own_property: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            desc: *mut JSPropertyDescriptor,
            obj: JSValue,
            prop: JSAtom,
        ) -> core::ffi::c_int,
    >,
    pub get_own_property_names: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            ptab: *mut *mut JSPropertyEnum,
            plen: *mut u32,
            obj: JSValue,
        ) -> core::ffi::c_int,
    >,
    pub delete_property: ::core::option::Option<
        unsafe extern "C" fn(ctx: *mut JSContext, obj: JSValue, prop: JSAtom) -> core::ffi::c_int,
    >,
    pub define_own_property: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            this_obj: JSValue,
            prop: JSAtom,
            val: JSValue,
            getter: JSValue,
            setter: JSValue,
            flags: core::ffi::c_int,
        ) -> core::ffi::c_int,
    >,
    pub has_property: ::core::option::Option<
        unsafe extern "C" fn(ctx: *mut JSContext, obj: JSValue, atom: JSAtom) -> core::ffi::c_int,
    >,
    pub get_property: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            obj: JSValue,
            atom: JSAtom,
            receiver: JSValue,
        ) -> JSValue,
    >,
    pub set_property: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            obj: JSValue,
            atom: JSAtom,
            value: JSValue,
            receiver: JSValue,
            flags: core::ffi::c_int,
        ) -> core::ffi::c_int,
    >,
}
pub type JSClassFinalizer =
    ::core::option::Option<unsafe extern "C" fn(rt: *mut JSRuntime, val: JSValue)>;
pub type JSClassGCMark = ::core::option::Option<
    unsafe extern "C" fn(rt: *mut JSRuntime, val: JSValue, mark_func: JS_MarkFunc),
>;
pub type JSClassCall = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        func_obj: JSValue,
        this_val: JSValue,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
        flags: core::ffi::c_int,
    ) -> JSValue,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSClassDef {
    pub class_name: *const core::ffi::c_char,
    pub finalizer: JSClassFinalizer,
    pub gc_mark: JSClassGCMark,
    pub call: JSClassCall,
    pub exotic: *mut JSClassExoticMethods,
}
impl Default for JSClassDef {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSEvalOptions {
    pub version: core::ffi::c_int,
    pub eval_flags: core::ffi::c_int,
    pub filename: *const core::ffi::c_char,
    pub line_num: core::ffi::c_int,
}
impl Default for JSEvalOptions {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn JS_NewClassID(rt: *mut JSRuntime, pclass_id: *mut JSClassID) -> JSClassID;
}
unsafe extern "C" {
    pub fn JS_GetClassID(v: JSValue) -> JSClassID;
}
unsafe extern "C" {
    pub fn JS_NewClass(
        rt: *mut JSRuntime,
        class_id: JSClassID,
        class_def: *const JSClassDef,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_IsRegisteredClass(rt: *mut JSRuntime, class_id: JSClassID) -> bool;
}
unsafe extern "C" {
    pub fn JS_GetClassName(rt: *mut JSRuntime, class_id: JSClassID) -> JSAtom;
}
unsafe extern "C" {
    #[link_name = "JS_NewBool__extern"]
    pub fn JS_NewBool(ctx: *mut JSContext, val: bool) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewInt32__extern"]
    pub fn JS_NewInt32(ctx: *mut JSContext, val: i32) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewFloat64__extern"]
    pub fn JS_NewFloat64(ctx: *mut JSContext, val: f64) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewCatchOffset__extern"]
    pub fn JS_NewCatchOffset(ctx: *mut JSContext, val: i32) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewInt64__extern"]
    pub fn JS_NewInt64(ctx: *mut JSContext, val: i64) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewUint32__extern"]
    pub fn JS_NewUint32(ctx: *mut JSContext, val: u32) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewUint64__extern"]
    pub fn JS_NewUint64(ctx: *mut JSContext, val: u64) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewNumber(ctx: *mut JSContext, d: f64) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewBigInt64(ctx: *mut JSContext, v: i64) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewBigUint64(ctx: *mut JSContext, v: u64) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_IsNumber__extern"]
    pub fn JS_IsNumber(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsBigInt__extern"]
    pub fn JS_IsBigInt(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsBool__extern"]
    pub fn JS_IsBool(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsNull__extern"]
    pub fn JS_IsNull(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsUndefined__extern"]
    pub fn JS_IsUndefined(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsException__extern"]
    pub fn JS_IsException(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsUninitialized__extern"]
    pub fn JS_IsUninitialized(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsString__extern"]
    pub fn JS_IsString(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsSymbol__extern"]
    pub fn JS_IsSymbol(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsObject__extern"]
    pub fn JS_IsObject(v: JSValue) -> bool;
}
unsafe extern "C" {
    #[link_name = "JS_IsModule__extern"]
    pub fn JS_IsModule(v: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_Throw(ctx: *mut JSContext, obj: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetException(ctx: *mut JSContext) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_HasException(ctx: *mut JSContext) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsError(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsUncatchableError(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_SetUncatchableError(ctx: *mut JSContext, val: JSValue);
}
unsafe extern "C" {
    pub fn JS_ClearUncatchableError(ctx: *mut JSContext, val: JSValue);
}
unsafe extern "C" {
    pub fn JS_ResetUncatchableError(ctx: *mut JSContext);
}
unsafe extern "C" {
    pub fn JS_NewError(ctx: *mut JSContext) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewInternalError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewPlainError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewRangeError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewReferenceError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...)
        -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewSyntaxError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewTypeError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ThrowInternalError(
        ctx: *mut JSContext,
        fmt: *const core::ffi::c_char,
        ...
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ThrowPlainError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ThrowRangeError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ThrowReferenceError(
        ctx: *mut JSContext,
        fmt: *const core::ffi::c_char,
        ...
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ThrowSyntaxError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ThrowTypeError(ctx: *mut JSContext, fmt: *const core::ffi::c_char, ...) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ThrowDOMException(
        ctx: *mut JSContext,
        name: *const core::ffi::c_char,
        fmt: *const core::ffi::c_char,
        ...
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ThrowOutOfMemory(ctx: *mut JSContext) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_FreeValue(ctx: *mut JSContext, v: JSValue);
}
unsafe extern "C" {
    pub fn JS_FreeValueRT(rt: *mut JSRuntime, v: JSValue);
}
unsafe extern "C" {
    pub fn JS_DupValue(ctx: *mut JSContext, v: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_DupValueRT(rt: *mut JSRuntime, v: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ToBool(ctx: *mut JSContext, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    #[link_name = "JS_ToBoolean__extern"]
    pub fn JS_ToBoolean(ctx: *mut JSContext, val: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ToNumber(ctx: *mut JSContext, val: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ToInt32(ctx: *mut JSContext, pres: *mut i32, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    #[link_name = "JS_ToUint32__extern"]
    pub fn JS_ToUint32(ctx: *mut JSContext, pres: *mut u32, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_ToInt64(ctx: *mut JSContext, pres: *mut i64, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_ToIndex(ctx: *mut JSContext, plen: *mut u64, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_ToFloat64(ctx: *mut JSContext, pres: *mut f64, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_ToBigInt64(ctx: *mut JSContext, pres: *mut i64, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_ToBigUint64(ctx: *mut JSContext, pres: *mut u64, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_ToInt64Ext(ctx: *mut JSContext, pres: *mut i64, val: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_NewStringLen(
        ctx: *mut JSContext,
        str1: *const core::ffi::c_char,
        len1: usize,
    ) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewString__extern"]
    pub fn JS_NewString(ctx: *mut JSContext, str_: *const core::ffi::c_char) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewStringUTF16(ctx: *mut JSContext, buf: *const u16, len: usize) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewAtomString(ctx: *mut JSContext, str_: *const core::ffi::c_char) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ToString(ctx: *mut JSContext, val: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ToPropertyKey(ctx: *mut JSContext, val: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ToCStringLen2(
        ctx: *mut JSContext,
        plen: *mut usize,
        val1: JSValue,
        cesu8: bool,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    #[link_name = "JS_ToCStringLen__extern"]
    pub fn JS_ToCStringLen(
        ctx: *mut JSContext,
        plen: *mut usize,
        val1: JSValue,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    #[link_name = "JS_ToCString__extern"]
    pub fn JS_ToCString(ctx: *mut JSContext, val1: JSValue) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn JS_ToCStringLenUTF16(ctx: *mut JSContext, plen: *mut usize, val1: JSValue)
        -> *const u16;
}
unsafe extern "C" {
    #[link_name = "JS_ToCStringUTF16__extern"]
    pub fn JS_ToCStringUTF16(ctx: *mut JSContext, val1: JSValue) -> *const u16;
}
unsafe extern "C" {
    pub fn JS_FreeCString(ctx: *mut JSContext, ptr: *const core::ffi::c_char);
}
unsafe extern "C" {
    pub fn JS_FreeCStringRT(rt: *mut JSRuntime, ptr: *const core::ffi::c_char);
}
unsafe extern "C" {
    pub fn JS_FreeCStringUTF16(ctx: *mut JSContext, ptr: *const u16);
}
unsafe extern "C" {
    pub fn JS_FreeCStringRT_UTF16(rt: *mut JSRuntime, ptr: *const u16);
}
unsafe extern "C" {
    pub fn JS_NewObjectProtoClass(
        ctx: *mut JSContext,
        proto: JSValue,
        class_id: JSClassID,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewObjectClass(ctx: *mut JSContext, class_id: JSClassID) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewObjectProto(ctx: *mut JSContext, proto: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewObject(ctx: *mut JSContext) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewObjectFrom(
        ctx: *mut JSContext,
        count: core::ffi::c_int,
        props: *const JSAtom,
        values: *const JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewObjectFromStr(
        ctx: *mut JSContext,
        count: core::ffi::c_int,
        props: *mut *const core::ffi::c_char,
        values: *const JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ToObject(ctx: *mut JSContext, val: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ToObjectString(ctx: *mut JSContext, val: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_IsFunction(ctx: *mut JSContext, val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsAsyncFunction(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsConstructor(ctx: *mut JSContext, val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_SetConstructorBit(ctx: *mut JSContext, func_obj: JSValue, val: bool) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsRegExp(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsMap(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsSet(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsWeakRef(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsWeakSet(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsWeakMap(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsDataView(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_NewArray(ctx: *mut JSContext) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewArrayFrom(
        ctx: *mut JSContext,
        count: core::ffi::c_int,
        values: *const JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_IsArray(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsProxy(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_GetProxyTarget(ctx: *mut JSContext, proxy: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetProxyHandler(ctx: *mut JSContext, proxy: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewProxy(ctx: *mut JSContext, target: JSValue, handler: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewDate(ctx: *mut JSContext, epoch_ms: f64) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_IsDate(v: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_GetProperty(ctx: *mut JSContext, this_obj: JSValue, prop: JSAtom) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetPropertyUint32(ctx: *mut JSContext, this_obj: JSValue, idx: u32) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetPropertyInt64(ctx: *mut JSContext, this_obj: JSValue, idx: i64) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetPropertyStr(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: *const core::ffi::c_char,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetPropertyValue(ctx: *mut JSContext, this_obj: JSValue, prop: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_SetProperty(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: JSAtom,
        val: JSValue,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetPropertyUint32(
        ctx: *mut JSContext,
        this_obj: JSValue,
        idx: u32,
        val: JSValue,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetPropertyInt64(
        ctx: *mut JSContext,
        this_obj: JSValue,
        idx: i64,
        val: JSValue,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetPropertyStr(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: *const core::ffi::c_char,
        val: JSValue,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetPropertyValue(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: JSValue,
        val: JSValue,
        flags: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_HasProperty(ctx: *mut JSContext, this_obj: JSValue, prop: JSAtom)
        -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_IsExtensible(ctx: *mut JSContext, obj: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_PreventExtensions(ctx: *mut JSContext, obj: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_DeleteProperty(
        ctx: *mut JSContext,
        obj: JSValue,
        prop: JSAtom,
        flags: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetPrototype(
        ctx: *mut JSContext,
        obj: JSValue,
        proto_val: JSValue,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_GetPrototype(ctx: *mut JSContext, val: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetLength(ctx: *mut JSContext, obj: JSValue, pres: *mut i64) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetLength(ctx: *mut JSContext, obj: JSValue, len: i64) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SealObject(ctx: *mut JSContext, obj: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_FreezeObject(ctx: *mut JSContext, obj: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_GetOwnPropertyNames(
        ctx: *mut JSContext,
        ptab: *mut *mut JSPropertyEnum,
        plen: *mut u32,
        obj: JSValue,
        flags: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_GetOwnProperty(
        ctx: *mut JSContext,
        desc: *mut JSPropertyDescriptor,
        obj: JSValue,
        prop: JSAtom,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_FreePropertyEnum(ctx: *mut JSContext, tab: *mut JSPropertyEnum, len: u32);
}
unsafe extern "C" {
    pub fn JS_Call(
        ctx: *mut JSContext,
        func_obj: JSValue,
        this_obj: JSValue,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_Invoke(
        ctx: *mut JSContext,
        this_val: JSValue,
        atom: JSAtom,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_CallConstructor(
        ctx: *mut JSContext,
        func_obj: JSValue,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_CallConstructor2(
        ctx: *mut JSContext,
        func_obj: JSValue,
        new_target: JSValue,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_DetectModule(input: *const core::ffi::c_char, input_len: usize) -> bool;
}
unsafe extern "C" {
    pub fn JS_Eval(
        ctx: *mut JSContext,
        input: *const core::ffi::c_char,
        input_len: usize,
        filename: *const core::ffi::c_char,
        eval_flags: core::ffi::c_int,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_Eval2(
        ctx: *mut JSContext,
        input: *const core::ffi::c_char,
        input_len: usize,
        options: *mut JSEvalOptions,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_EvalThis(
        ctx: *mut JSContext,
        this_obj: JSValue,
        input: *const core::ffi::c_char,
        input_len: usize,
        filename: *const core::ffi::c_char,
        eval_flags: core::ffi::c_int,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_EvalThis2(
        ctx: *mut JSContext,
        this_obj: JSValue,
        input: *const core::ffi::c_char,
        input_len: usize,
        options: *mut JSEvalOptions,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetGlobalObject(ctx: *mut JSContext) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_IsInstanceOf(ctx: *mut JSContext, val: JSValue, obj: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_DefineProperty(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: JSAtom,
        val: JSValue,
        getter: JSValue,
        setter: JSValue,
        flags: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_DefinePropertyValue(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: JSAtom,
        val: JSValue,
        flags: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_DefinePropertyValueUint32(
        ctx: *mut JSContext,
        this_obj: JSValue,
        idx: u32,
        val: JSValue,
        flags: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_DefinePropertyValueStr(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: *const core::ffi::c_char,
        val: JSValue,
        flags: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_DefinePropertyGetSet(
        ctx: *mut JSContext,
        this_obj: JSValue,
        prop: JSAtom,
        getter: JSValue,
        setter: JSValue,
        flags: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetOpaque(obj: JSValue, opaque: *mut core::ffi::c_void) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_GetOpaque(obj: JSValue, class_id: JSClassID) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn JS_GetOpaque2(
        ctx: *mut JSContext,
        obj: JSValue,
        class_id: JSClassID,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn JS_GetAnyOpaque(obj: JSValue, class_id: *mut JSClassID) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn JS_ParseJSON(
        ctx: *mut JSContext,
        buf: *const core::ffi::c_char,
        buf_len: usize,
        filename: *const core::ffi::c_char,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_JSONStringify(
        ctx: *mut JSContext,
        obj: JSValue,
        replacer: JSValue,
        space0: JSValue,
    ) -> JSValue;
}
pub type JSReallocArrayBufferDataFunc = ::core::option::Option<
    unsafe extern "C" fn(
        rt: *mut JSRuntime,
        opaque: *mut core::ffi::c_void,
        ptr: *mut core::ffi::c_void,
        size: usize,
    ) -> *mut core::ffi::c_void,
>;
unsafe extern "C" {
    pub fn JS_NewArrayBuffer(
        ctx: *mut JSContext,
        buf: *mut u8,
        len: usize,
        max_len: usize,
        realloc_func: JSReallocArrayBufferDataFunc,
        opaque: *mut core::ffi::c_void,
        is_shared: bool,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewArrayBufferCopy(ctx: *mut JSContext, buf: *const u8, len: usize) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_DetachArrayBuffer(ctx: *mut JSContext, obj: JSValue);
}
unsafe extern "C" {
    pub fn JS_GetArrayBuffer(ctx: *mut JSContext, psize: *mut usize, obj: JSValue) -> *mut u8;
}
unsafe extern "C" {
    pub fn JS_IsArrayBuffer(obj: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_IsImmutableArrayBuffer(obj: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetImmutableArrayBuffer(obj: JSValue, immutable: bool) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_GetUint8Array(ctx: *mut JSContext, psize: *mut usize, obj: JSValue) -> *mut u8;
}
pub const JS_TYPED_ARRAY_UINT8C: JSTypedArrayEnum = 0;
pub const JS_TYPED_ARRAY_INT8: JSTypedArrayEnum = 1;
pub const JS_TYPED_ARRAY_UINT8: JSTypedArrayEnum = 2;
pub const JS_TYPED_ARRAY_INT16: JSTypedArrayEnum = 3;
pub const JS_TYPED_ARRAY_UINT16: JSTypedArrayEnum = 4;
pub const JS_TYPED_ARRAY_INT32: JSTypedArrayEnum = 5;
pub const JS_TYPED_ARRAY_UINT32: JSTypedArrayEnum = 6;
pub const JS_TYPED_ARRAY_BIG_INT64: JSTypedArrayEnum = 7;
pub const JS_TYPED_ARRAY_BIG_UINT64: JSTypedArrayEnum = 8;
pub const JS_TYPED_ARRAY_FLOAT16: JSTypedArrayEnum = 9;
pub const JS_TYPED_ARRAY_FLOAT32: JSTypedArrayEnum = 10;
pub const JS_TYPED_ARRAY_FLOAT64: JSTypedArrayEnum = 11;
pub type JSTypedArrayEnum = core::ffi::c_uint;
unsafe extern "C" {
    pub fn JS_NewTypedArray(
        ctx: *mut JSContext,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
        array_type: JSTypedArrayEnum,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetTypedArrayBuffer(
        ctx: *mut JSContext,
        obj: JSValue,
        pbyte_offset: *mut usize,
        pbyte_length: *mut usize,
        pbytes_per_element: *mut usize,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewUint8Array(
        ctx: *mut JSContext,
        buf: *mut u8,
        len: usize,
        realloc_func: JSReallocArrayBufferDataFunc,
        opaque: *mut core::ffi::c_void,
        is_shared: bool,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetTypedArrayType(obj: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_NewUint8ArrayCopy(ctx: *mut JSContext, buf: *const u8, len: usize) -> JSValue;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSSharedArrayBufferFunctions {
    pub sab_alloc: ::core::option::Option<
        unsafe extern "C" fn(opaque: *mut core::ffi::c_void, size: usize) -> *mut core::ffi::c_void,
    >,
    pub sab_free: ::core::option::Option<
        unsafe extern "C" fn(opaque: *mut core::ffi::c_void, ptr: *mut core::ffi::c_void),
    >,
    pub sab_dup: ::core::option::Option<
        unsafe extern "C" fn(opaque: *mut core::ffi::c_void, ptr: *mut core::ffi::c_void),
    >,
    pub sab_opaque: *mut core::ffi::c_void,
}
impl Default for JSSharedArrayBufferFunctions {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn JS_SetSharedArrayBufferFunctions(
        rt: *mut JSRuntime,
        sf: *const JSSharedArrayBufferFunctions,
    );
}
pub const JS_PROMISE_NOT_A_PROMISE: JSPromiseStateEnum = -1;
pub const JS_PROMISE_PENDING: JSPromiseStateEnum = 0;
pub const JS_PROMISE_FULFILLED: JSPromiseStateEnum = 1;
pub const JS_PROMISE_REJECTED: JSPromiseStateEnum = 2;
pub type JSPromiseStateEnum = core::ffi::c_int;
unsafe extern "C" {
    pub fn JS_NewPromiseCapability(ctx: *mut JSContext, resolving_funcs: *mut JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_PromiseThen(
        ctx: *mut JSContext,
        promise: JSValue,
        on_fulfilled: JSValue,
        on_rejected: JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_PromiseState(ctx: *mut JSContext, promise: JSValue) -> JSPromiseStateEnum;
}
unsafe extern "C" {
    pub fn JS_PromiseResult(ctx: *mut JSContext, promise: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_IsPromise(val: JSValue) -> bool;
}
unsafe extern "C" {
    pub fn JS_PromiseMarkAsHandled(ctx: *mut JSContext, promise: JSValue);
}
unsafe extern "C" {
    pub fn JS_NewSettledPromise(ctx: *mut JSContext, is_reject: bool, value: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewSymbol(
        ctx: *mut JSContext,
        description: *const core::ffi::c_char,
        is_global: bool,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewPrivateSymbol(
        ctx: *mut JSContext,
        description: *const core::ffi::c_char,
    ) -> JSValue;
}
pub const JS_PROMISE_HOOK_INIT: JSPromiseHookType = 0;
pub const JS_PROMISE_HOOK_BEFORE: JSPromiseHookType = 1;
pub const JS_PROMISE_HOOK_AFTER: JSPromiseHookType = 2;
pub const JS_PROMISE_HOOK_RESOLVE: JSPromiseHookType = 3;
pub type JSPromiseHookType = core::ffi::c_uint;
pub type JSPromiseHook = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        type_: JSPromiseHookType,
        promise: JSValue,
        parent_promise: JSValue,
        opaque: *mut core::ffi::c_void,
    ),
>;
unsafe extern "C" {
    pub fn JS_SetPromiseHook(
        rt: *mut JSRuntime,
        promise_hook: JSPromiseHook,
        opaque: *mut core::ffi::c_void,
    );
}
pub type JSHostPromiseRejectionTracker = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        promise: JSValue,
        reason: JSValue,
        is_handled: bool,
        opaque: *mut core::ffi::c_void,
    ),
>;
unsafe extern "C" {
    pub fn JS_SetHostPromiseRejectionTracker(
        rt: *mut JSRuntime,
        cb: JSHostPromiseRejectionTracker,
        opaque: *mut core::ffi::c_void,
    );
}
pub type JSInterruptHandler = ::core::option::Option<
    unsafe extern "C" fn(rt: *mut JSRuntime, opaque: *mut core::ffi::c_void) -> core::ffi::c_int,
>;
unsafe extern "C" {
    pub fn JS_SetInterruptHandler(
        rt: *mut JSRuntime,
        cb: JSInterruptHandler,
        opaque: *mut core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn JS_SetCanBlock(rt: *mut JSRuntime, can_block: bool);
}
unsafe extern "C" {
    pub fn JS_SetIsHTMLDDA(ctx: *mut JSContext, obj: JSValue);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSModuleDef {
    _unused: [u8; 0],
}
pub type JSModuleNormalizeFunc = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        module_base_name: *const core::ffi::c_char,
        module_name: *const core::ffi::c_char,
        opaque: *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_char,
>;
pub type JSModuleNormalizeFunc2 = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        module_base_name: *const core::ffi::c_char,
        module_name: *const core::ffi::c_char,
        attributes: JSValue,
        opaque: *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_char,
>;
pub type JSModuleLoaderFunc = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        module_name: *const core::ffi::c_char,
        opaque: *mut core::ffi::c_void,
    ) -> *mut JSModuleDef,
>;
pub type JSModuleLoaderFunc2 = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        module_name: *const core::ffi::c_char,
        opaque: *mut core::ffi::c_void,
        attributes: JSValue,
    ) -> *mut JSModuleDef,
>;
pub type JSModuleCheckSupportedImportAttributes = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        opaque: *mut core::ffi::c_void,
        attributes: JSValue,
    ) -> core::ffi::c_int,
>;
unsafe extern "C" {
    pub fn JS_SetModuleLoaderFunc(
        rt: *mut JSRuntime,
        module_normalize: JSModuleNormalizeFunc,
        module_loader: JSModuleLoaderFunc,
        opaque: *mut core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn JS_SetModuleLoaderFunc2(
        rt: *mut JSRuntime,
        module_normalize: JSModuleNormalizeFunc,
        module_loader: JSModuleLoaderFunc2,
        module_check_attrs: JSModuleCheckSupportedImportAttributes,
        opaque: *mut core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn JS_SetModuleNormalizeFunc2(rt: *mut JSRuntime, module_normalize: JSModuleNormalizeFunc2);
}
unsafe extern "C" {
    pub fn JS_GetImportMeta(ctx: *mut JSContext, m: *mut JSModuleDef) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_GetModuleName(ctx: *mut JSContext, m: *mut JSModuleDef) -> JSAtom;
}
unsafe extern "C" {
    pub fn JS_GetModuleNamespace(ctx: *mut JSContext, m: *mut JSModuleDef) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_SetModulePrivateValue(
        ctx: *mut JSContext,
        m: *mut JSModuleDef,
        val: JSValue,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_GetModulePrivateValue(ctx: *mut JSContext, m: *mut JSModuleDef) -> JSValue;
}
pub type JSJobFunc = ::core::option::Option<
    unsafe extern "C" fn(
        ctx: *mut JSContext,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
    ) -> JSValue,
>;
unsafe extern "C" {
    pub fn JS_EnqueueJob(
        ctx: *mut JSContext,
        job_func: JSJobFunc,
        argc: core::ffi::c_int,
        argv: *mut JSValue,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_IsJobPending(rt: *mut JSRuntime) -> bool;
}
unsafe extern "C" {
    pub fn JS_GetPendingJobContext(rt: *mut JSRuntime) -> *mut JSContext;
}
unsafe extern "C" {
    pub fn JS_ExecutePendingJob(rt: *mut JSRuntime, pctx: *mut *mut JSContext) -> core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSSABTab {
    pub tab: *mut *mut u8,
    pub len: usize,
}
impl Default for JSSABTab {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn JS_WriteObject(
        ctx: *mut JSContext,
        psize: *mut usize,
        obj: JSValue,
        flags: core::ffi::c_int,
    ) -> *mut u8;
}
unsafe extern "C" {
    pub fn JS_WriteObject2(
        ctx: *mut JSContext,
        psize: *mut usize,
        obj: JSValue,
        flags: core::ffi::c_int,
        psab_tab: *mut JSSABTab,
    ) -> *mut u8;
}
unsafe extern "C" {
    pub fn JS_ReadObject(
        ctx: *mut JSContext,
        buf: *const u8,
        buf_len: usize,
        flags: core::ffi::c_int,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ReadObject2(
        ctx: *mut JSContext,
        buf: *const u8,
        buf_len: usize,
        flags: core::ffi::c_int,
        psab_tab: *mut JSSABTab,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_EvalFunction(ctx: *mut JSContext, fun_obj: JSValue) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_ResolveModule(ctx: *mut JSContext, obj: JSValue) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_GetScriptOrModuleName(
        ctx: *mut JSContext,
        n_stack_levels: core::ffi::c_int,
    ) -> JSAtom;
}
unsafe extern "C" {
    pub fn JS_LoadModule(
        ctx: *mut JSContext,
        basename: *const core::ffi::c_char,
        filename: *const core::ffi::c_char,
    ) -> JSValue;
}
pub const JS_CFUNC_generic: JSCFunctionEnum = 0;
pub const JS_CFUNC_generic_magic: JSCFunctionEnum = 1;
pub const JS_CFUNC_constructor: JSCFunctionEnum = 2;
pub const JS_CFUNC_constructor_magic: JSCFunctionEnum = 3;
pub const JS_CFUNC_constructor_or_func: JSCFunctionEnum = 4;
pub const JS_CFUNC_constructor_or_func_magic: JSCFunctionEnum = 5;
pub const JS_CFUNC_f_f: JSCFunctionEnum = 6;
pub const JS_CFUNC_f_f_f: JSCFunctionEnum = 7;
pub const JS_CFUNC_getter: JSCFunctionEnum = 8;
pub const JS_CFUNC_setter: JSCFunctionEnum = 9;
pub const JS_CFUNC_getter_magic: JSCFunctionEnum = 10;
pub const JS_CFUNC_setter_magic: JSCFunctionEnum = 11;
pub const JS_CFUNC_iterator_next: JSCFunctionEnum = 12;
pub type JSCFunctionEnum = core::ffi::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub union JSCFunctionType {
    pub generic: JSCFunction,
    pub generic_magic: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            this_val: JSValue,
            argc: core::ffi::c_int,
            argv: *mut JSValue,
            magic: core::ffi::c_int,
        ) -> JSValue,
    >,
    pub constructor: JSCFunction,
    pub constructor_magic: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            new_target: JSValue,
            argc: core::ffi::c_int,
            argv: *mut JSValue,
            magic: core::ffi::c_int,
        ) -> JSValue,
    >,
    pub constructor_or_func: JSCFunction,
    pub f_f: ::core::option::Option<unsafe extern "C" fn(arg1: f64) -> f64>,
    pub f_f_f: ::core::option::Option<unsafe extern "C" fn(arg1: f64, arg2: f64) -> f64>,
    pub getter: ::core::option::Option<
        unsafe extern "C" fn(ctx: *mut JSContext, this_val: JSValue) -> JSValue,
    >,
    pub setter: ::core::option::Option<
        unsafe extern "C" fn(ctx: *mut JSContext, this_val: JSValue, val: JSValue) -> JSValue,
    >,
    pub getter_magic: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            this_val: JSValue,
            magic: core::ffi::c_int,
        ) -> JSValue,
    >,
    pub setter_magic: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            this_val: JSValue,
            val: JSValue,
            magic: core::ffi::c_int,
        ) -> JSValue,
    >,
    pub iterator_next: ::core::option::Option<
        unsafe extern "C" fn(
            ctx: *mut JSContext,
            this_val: JSValue,
            argc: core::ffi::c_int,
            argv: *mut JSValue,
            pdone: *mut core::ffi::c_int,
            magic: core::ffi::c_int,
        ) -> JSValue,
    >,
}
impl Default for JSCFunctionType {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn JS_NewCFunction2(
        ctx: *mut JSContext,
        func: JSCFunction,
        name: *const core::ffi::c_char,
        length: core::ffi::c_int,
        cproto: JSCFunctionEnum,
        magic: core::ffi::c_int,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewCFunction3(
        ctx: *mut JSContext,
        func: JSCFunction,
        name: *const core::ffi::c_char,
        length: core::ffi::c_int,
        cproto: JSCFunctionEnum,
        magic: core::ffi::c_int,
        proto_val: JSValue,
        n_fields: core::ffi::c_int,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewCFunctionData(
        ctx: *mut JSContext,
        func: JSCFunctionData,
        length: core::ffi::c_int,
        magic: core::ffi::c_int,
        data_len: core::ffi::c_int,
        data: *mut JSValue,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_NewCFunctionData2(
        ctx: *mut JSContext,
        func: JSCFunctionData,
        name: *const core::ffi::c_char,
        length: core::ffi::c_int,
        magic: core::ffi::c_int,
        data_len: core::ffi::c_int,
        data: *mut JSValue,
    ) -> JSValue;
}
pub type JSCClosureFinalizerFunc =
    ::core::option::Option<unsafe extern "C" fn(arg1: *mut core::ffi::c_void)>;
unsafe extern "C" {
    pub fn JS_NewCClosure(
        ctx: *mut JSContext,
        func: JSCClosure,
        name: *const core::ffi::c_char,
        opaque_finalize: JSCClosureFinalizerFunc,
        length: core::ffi::c_int,
        magic: core::ffi::c_int,
        opaque: *mut core::ffi::c_void,
    ) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewCFunction__extern"]
    pub fn JS_NewCFunction(
        ctx: *mut JSContext,
        func: JSCFunction,
        name: *const core::ffi::c_char,
        length: core::ffi::c_int,
    ) -> JSValue;
}
unsafe extern "C" {
    #[link_name = "JS_NewCFunctionMagic__extern"]
    pub fn JS_NewCFunctionMagic(
        ctx: *mut JSContext,
        func: JSCFunctionMagic,
        name: *const core::ffi::c_char,
        length: core::ffi::c_int,
        cproto: JSCFunctionEnum,
        magic: core::ffi::c_int,
    ) -> JSValue;
}
unsafe extern "C" {
    pub fn JS_SetConstructor(
        ctx: *mut JSContext,
        func_obj: JSValue,
        proto: JSValue,
    ) -> core::ffi::c_int;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct JSCFunctionListEntry {
    pub name: *const core::ffi::c_char,
    pub prop_flags: u8,
    pub def_type: u8,
    pub magic: i16,
    pub u: JSCFunctionListEntry__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union JSCFunctionListEntry__bindgen_ty_1 {
    pub func: JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_1,
    pub getset: JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_2,
    pub alias: JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_3,
    pub prop_list: JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_4,
    pub str_: *const core::ffi::c_char,
    pub i32_: i32,
    pub i64_: i64,
    pub u64_: u64,
    pub f64_: f64,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_1 {
    pub length: u8,
    pub cproto: u8,
    pub cfunc: JSCFunctionType,
}
impl Default for JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_2 {
    pub get: JSCFunctionType,
    pub set: JSCFunctionType,
}
impl Default for JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_3 {
    pub name: *const core::ffi::c_char,
    pub base: core::ffi::c_int,
}
impl Default for JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_3 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_4 {
    pub tab: *const JSCFunctionListEntry,
    pub len: core::ffi::c_int,
}
impl Default for JSCFunctionListEntry__bindgen_ty_1__bindgen_ty_4 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for JSCFunctionListEntry__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for JSCFunctionListEntry {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn JS_SetPropertyFunctionList(
        ctx: *mut JSContext,
        obj: JSValue,
        tab: *const JSCFunctionListEntry,
        len: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
pub type JSModuleInitFunc = ::core::option::Option<
    unsafe extern "C" fn(ctx: *mut JSContext, m: *mut JSModuleDef) -> core::ffi::c_int,
>;
unsafe extern "C" {
    pub fn JS_NewCModule(
        ctx: *mut JSContext,
        name_str: *const core::ffi::c_char,
        func: JSModuleInitFunc,
    ) -> *mut JSModuleDef;
}
unsafe extern "C" {
    pub fn JS_AddModuleExport(
        ctx: *mut JSContext,
        m: *mut JSModuleDef,
        name_str: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_AddModuleExportList(
        ctx: *mut JSContext,
        m: *mut JSModuleDef,
        tab: *const JSCFunctionListEntry,
        len: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetModuleExport(
        ctx: *mut JSContext,
        m: *mut JSModuleDef,
        export_name: *const core::ffi::c_char,
        val: JSValue,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_SetModuleExportList(
        ctx: *mut JSContext,
        m: *mut JSModuleDef,
        tab: *const JSCFunctionListEntry,
        len: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn JS_GetVersion() -> *const core::ffi::c_char;
}
