[package]
name = "karna"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["assets","engine", "gpu", "image", "imgui","logging", "math", "renderer", "utils"]

[workspace.dependencies]
parking_lot = "0.12.5"
wgpu = { version = "30.0.0", default-features = false, features = ["wgsl", "vulkan"] }
utils = { path = "utils" }
winit = "0.30.13"
math = {path = "math" }
logging = { path = "logging" }
gpu = { path = "gpu" }
renderer = { path = "renderer" }
assets = { path = "assets" }
imgui = { path = "imgui" }
rodio = "0.22.2"
crossbeam-channel = "0.5.16"
image = { path = "image" }

[dependencies]
logging.workspace = true
engine = { path = "engine" }
math.workspace = true
renderer.workspace = true
assets.workspace = true
utils.workspace = true
imgui.workspace = true
gpu.workspace = true

[dev-dependencies]
log = "0.4.33"
serde = { version = "1.0.228", features = ["derive"] }

[features]
net = ["engine/net", "math/serde"]
