[package]
name = "karna"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["math", "logging", "utils", "engine", "gpu", "imgui"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
gpu = { path = "gpu" }
logging = { path = "logging" }
math = { path = "math" }
utils = { path = "utils" }

crossbeam-channel = "0.5.16"
sdl3 = { version = "0.18.4", features = ["image", "ttf", "mixer"] }
sdl3-mixer-sys = { version = "0.6.3", features = ["build-static-vendored"] }
parking_lot = "0.12.5"

[dependencies]
engine = { path = "engine" }
gpu.workspace = true
logging.workspace = true
math.workspace = true
utils.workspace = true

[dev-dependencies]
