[package]
name = "karna-cli"
description = "Command line tools for the karna engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "karna"
path = "src/main.rs"

[features]
default = ["build-from-source"]
build-from-source = ["karna/build-from-source"]

[dependencies]
karna.workspace = true
