[package]
name = "karna-cli"
description = "Command line tools for the karna engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "karna"
path = "src/main.rs"

[features]
default = ["build-from-source"]
build-from-source = [
    "karna-sdl3/build-from-source",
    "karna/build-from-source",
    "karna-quickjs/build-from-source",
]
dxc = ["karna-sdl3/dxc"]

[dependencies]
karna-sdl3.workspace = true
karna = { workspace = true, features = ["js"] }
karna-quickjs.workspace = true
karna-nostd.workspace = true
traccia.workspace = true
lexopt = "0.3.2"
