[package]
name = "karna-engine"
description = "Internal engine crate for the karna engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "engine"
path = "src/lib.rs"

[features]
default = ["build-from-source"]
build-from-source = ["karna-sdl3/build-from-source"]

[dependencies]
karna-sdl3 = { workspace = true, features = ["shadercross"] }
karna-nostd.workspace = true
karna-math.workspace = true
karna-utils.workspace = true
karna-quickjs-sys.workspace = true
traccia.workspace = true
cosmic-text = { version =  "0.19.0", default-features = false, features = ["no_std", "swash"] }
