[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
winit.workspace = true
parking_lot.workspace = true
math.workspace = true
assets.workspace = true
logging.workspace = true
utils.workspace = true
gpu.workspace = true
renderer.workspace = true
imgui.workspace = true
crossbeam-channel.workspace = true
glyph_brush_layout = "0.2.4"
serde = { version = "1.0.228", optional = true }
postcard = { version = "1.1.3", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rodio = { workspace = true, features = ["playback"] }
pollster = "0.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
web-time = "1.1"
console_error_panic_hook = "0.1"

[features]
net = ["dep:serde", "dep:postcard", "math/serde"]
