[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
math.workspace = true
winit.workspace = true
utils.workspace = true
gpu.workspace = true
macros.workspace = true
logging.workspace = true
crossbeam-channel = "0.5.15"
globals.workspace = true
renderer.workspace = true
spin_sleep = "1.3.3"
wgpu.workspace = true
