[package]
name = "karna-nostd"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "nostd"
path = "src/lib.rs"

[dependencies]
karna-sdl3-sys.workspace = true
hashbrown = { version = "0.17.1", default-features = false }
traccia.workspace = true
