[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
num = "0.4.3"
winit.workspace = true

[dev-dependencies]
const-random = "0.1.18"
nalgebra = "0.33.2"

[lib]
doctest = false
