[package]
name = "quickjs"
version.workspace = true
edition.workspace = true

[dependencies]
engine.workspace = true
logging.workspace = true
math.workspace = true
utils.workspace = true

rquickjs = { version = "0.12", features = ["macro", "classes", "properties", "loader"] }

[dev-dependencies]
rquickjs = { version = "0.12", features = ["macro", "classes", "properties", "loader"] }
