/* automatically generated by rust-bindgen 0.72.1 */

pub const LUA_AUTHORS: &[u8; 48] = b"R. Ierusalimschy, L. H. de Figueiredo, W. Celes\0";
pub const LUA_VERSION_MAJOR_N: i32 = 5;
pub const LUA_VERSION_MINOR_N: i32 = 5;
pub const LUA_VERSION_RELEASE_N: i32 = 1;
pub const LUA_VERSION_NUM: i32 = 505;
pub const LUA_VERSION_RELEASE_NUM: i32 = 50501;
pub const LUA_INT_INT: i32 = 1;
pub const LUA_INT_LONG: i32 = 2;
pub const LUA_INT_LONGLONG: i32 = 3;
pub const LUA_FLOAT_FLOAT: i32 = 1;
pub const LUA_FLOAT_DOUBLE: i32 = 2;
pub const LUA_FLOAT_LONGDOUBLE: i32 = 3;
pub const LUA_INT_DEFAULT: i32 = 3;
pub const LUA_FLOAT_DEFAULT: i32 = 2;
pub const LUA_C89_NUMBERS: i32 = 0;
pub const LUA_INT_TYPE: i32 = 3;
pub const LUA_FLOAT_TYPE: i32 = 2;
pub const LUA_PATH_SEP: &[u8; 2] = b";\0";
pub const LUA_PATH_MARK: &[u8; 2] = b"?\0";
pub const LUA_EXEC_DIR: &[u8; 2] = b"!\0";
pub const LUA_ROOT: &[u8; 12] = b"/usr/local/\0";
pub const LUA_DIRSEP: &[u8; 2] = b"/\0";
pub const LUA_IGMARK: &[u8; 2] = b"-\0";
pub const LUA_COMPAT_GLOBAL: i32 = 1;
pub const LUA_NUMBER_FRMLEN: &[u8; 1] = b"\0";
pub const LUA_NUMBER_FMT: &[u8; 6] = b"%.15g\0";
pub const LUA_NUMBER_FMT_N: &[u8; 6] = b"%.17g\0";
pub const LUA_INTEGER_FRMLEN: &[u8; 3] = b"ll\0";
pub const LUA_IDSIZE: i32 = 60;
pub const LUA_SIGNATURE: &[u8; 5] = b"\x1BLua\0";
pub const LUA_MULTRET: i32 = -1;
pub const LUA_OK: i32 = 0;
pub const LUA_YIELD: i32 = 1;
pub const LUA_ERRRUN: i32 = 2;
pub const LUA_ERRSYNTAX: i32 = 3;
pub const LUA_ERRMEM: i32 = 4;
pub const LUA_ERRERR: i32 = 5;
pub const LUA_TNONE: i32 = -1;
pub const LUA_TNIL: i32 = 0;
pub const LUA_TBOOLEAN: i32 = 1;
pub const LUA_TLIGHTUSERDATA: i32 = 2;
pub const LUA_TNUMBER: i32 = 3;
pub const LUA_TSTRING: i32 = 4;
pub const LUA_TTABLE: i32 = 5;
pub const LUA_TFUNCTION: i32 = 6;
pub const LUA_TUSERDATA: i32 = 7;
pub const LUA_TTHREAD: i32 = 8;
pub const LUA_NUMTYPES: i32 = 9;
pub const LUA_MINSTACK: i32 = 20;
pub const LUA_RIDX_GLOBALS: i32 = 2;
pub const LUA_RIDX_MAINTHREAD: i32 = 3;
pub const LUA_RIDX_LAST: i32 = 3;
pub const LUA_OPADD: i32 = 0;
pub const LUA_OPSUB: i32 = 1;
pub const LUA_OPMUL: i32 = 2;
pub const LUA_OPMOD: i32 = 3;
pub const LUA_OPPOW: i32 = 4;
pub const LUA_OPDIV: i32 = 5;
pub const LUA_OPIDIV: i32 = 6;
pub const LUA_OPBAND: i32 = 7;
pub const LUA_OPBOR: i32 = 8;
pub const LUA_OPBXOR: i32 = 9;
pub const LUA_OPSHL: i32 = 10;
pub const LUA_OPSHR: i32 = 11;
pub const LUA_OPUNM: i32 = 12;
pub const LUA_OPBNOT: i32 = 13;
pub const LUA_OPEQ: i32 = 0;
pub const LUA_OPLT: i32 = 1;
pub const LUA_OPLE: i32 = 2;
pub const LUA_GCSTOP: i32 = 0;
pub const LUA_GCRESTART: i32 = 1;
pub const LUA_GCCOLLECT: i32 = 2;
pub const LUA_GCCOUNT: i32 = 3;
pub const LUA_GCCOUNTB: i32 = 4;
pub const LUA_GCSTEP: i32 = 5;
pub const LUA_GCISRUNNING: i32 = 6;
pub const LUA_GCGEN: i32 = 7;
pub const LUA_GCINC: i32 = 8;
pub const LUA_GCPARAM: i32 = 9;
pub const LUA_GCPMINORMUL: i32 = 0;
pub const LUA_GCPMAJORMINOR: i32 = 1;
pub const LUA_GCPMINORMAJOR: i32 = 2;
pub const LUA_GCPPAUSE: i32 = 3;
pub const LUA_GCPSTEPMUL: i32 = 4;
pub const LUA_GCPSTEPSIZE: i32 = 5;
pub const LUA_GCPN: i32 = 6;
pub const LUA_N2SBUFFSZ: i32 = 64;
pub const LUA_HOOKCALL: i32 = 0;
pub const LUA_HOOKRET: i32 = 1;
pub const LUA_HOOKLINE: i32 = 2;
pub const LUA_HOOKCOUNT: i32 = 3;
pub const LUA_HOOKTAILCALL: i32 = 4;
pub const LUA_MASKCALL: i32 = 1;
pub const LUA_MASKRET: i32 = 2;
pub const LUA_MASKLINE: i32 = 4;
pub const LUA_MASKCOUNT: i32 = 8;
pub const LUA_GNAME: &[u8; 3] = b"_G\0";
pub const LUA_ERRFILE: i32 = 6;
pub const LUA_LOADED_TABLE: &[u8; 8] = b"_LOADED\0";
pub const LUA_PRELOAD_TABLE: &[u8; 9] = b"_PRELOAD\0";
pub const LUA_NOREF: i32 = -2;
pub const LUA_REFNIL: i32 = -1;
pub const LUA_FILEHANDLE: &[u8; 6] = b"FILE*\0";
pub const LUA_GLIBK: i32 = 1;
pub const LUA_LOADLIBNAME: &[u8; 8] = b"package\0";
pub const LUA_LOADLIBK: i32 = 2;
pub const LUA_COLIBNAME: &[u8; 10] = b"coroutine\0";
pub const LUA_COLIBK: i32 = 4;
pub const LUA_DBLIBNAME: &[u8; 6] = b"debug\0";
pub const LUA_DBLIBK: i32 = 8;
pub const LUA_IOLIBNAME: &[u8; 3] = b"io\0";
pub const LUA_IOLIBK: i32 = 16;
pub const LUA_MATHLIBNAME: &[u8; 5] = b"math\0";
pub const LUA_MATHLIBK: i32 = 32;
pub const LUA_OSLIBNAME: &[u8; 3] = b"os\0";
pub const LUA_OSLIBK: i32 = 64;
pub const LUA_STRLIBNAME: &[u8; 7] = b"string\0";
pub const LUA_STRLIBK: i32 = 128;
pub const LUA_TABLIBNAME: &[u8; 6] = b"table\0";
pub const LUA_TABLIBK: i32 = 256;
pub const LUA_UTF8LIBNAME: &[u8; 5] = b"utf8\0";
pub const LUA_UTF8LIBK: i32 = 512;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_State {
    _unused: [u8; 0],
}
pub type lua_Number = f64;
pub type lua_Integer = core::ffi::c_longlong;
pub type lua_Unsigned = core::ffi::c_ulonglong;
pub type lua_KContext = isize;
pub type lua_CFunction =
    ::core::option::Option<unsafe extern "C" fn(L: *mut lua_State) -> core::ffi::c_int>;
pub type lua_KFunction = ::core::option::Option<
    unsafe extern "C" fn(
        L: *mut lua_State,
        status: core::ffi::c_int,
        ctx: lua_KContext,
    ) -> core::ffi::c_int,
>;
pub type lua_Reader = ::core::option::Option<
    unsafe extern "C" fn(
        L: *mut lua_State,
        ud: *mut core::ffi::c_void,
        sz: *mut usize,
    ) -> *const core::ffi::c_char,
>;
pub type lua_Writer = ::core::option::Option<
    unsafe extern "C" fn(
        L: *mut lua_State,
        p: *const core::ffi::c_void,
        sz: usize,
        ud: *mut core::ffi::c_void,
    ) -> core::ffi::c_int,
>;
pub type lua_Alloc = ::core::option::Option<
    unsafe extern "C" fn(
        ud: *mut core::ffi::c_void,
        ptr: *mut core::ffi::c_void,
        osize: usize,
        nsize: usize,
    ) -> *mut core::ffi::c_void,
>;
pub type lua_WarnFunction = ::core::option::Option<
    unsafe extern "C" fn(
        ud: *mut core::ffi::c_void,
        msg: *const core::ffi::c_char,
        tocont: core::ffi::c_int,
    ),
>;
pub type lua_Hook =
    ::core::option::Option<unsafe extern "C" fn(L: *mut lua_State, ar: *mut lua_Debug)>;
unsafe extern "C" {
    pub fn lua_newstate(
        f: lua_Alloc,
        ud: *mut core::ffi::c_void,
        seed: core::ffi::c_uint,
    ) -> *mut lua_State;
}
unsafe extern "C" {
    pub fn lua_close(L: *mut lua_State);
}
unsafe extern "C" {
    pub fn lua_newthread(L: *mut lua_State) -> *mut lua_State;
}
unsafe extern "C" {
    pub fn lua_closethread(L: *mut lua_State, from: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_atpanic(L: *mut lua_State, panicf: lua_CFunction) -> lua_CFunction;
}
unsafe extern "C" {
    pub fn lua_version(L: *mut lua_State) -> lua_Number;
}
unsafe extern "C" {
    pub fn lua_absindex(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_gettop(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_settop(L: *mut lua_State, idx: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_pushvalue(L: *mut lua_State, idx: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_rotate(L: *mut lua_State, idx: core::ffi::c_int, n: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_copy(L: *mut lua_State, fromidx: core::ffi::c_int, toidx: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_checkstack(L: *mut lua_State, n: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_xmove(from: *mut lua_State, to: *mut lua_State, n: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_isnumber(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_isstring(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_iscfunction(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_isinteger(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_isuserdata(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_type(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_typename(L: *mut lua_State, tp: core::ffi::c_int) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_tonumberx(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        isnum: *mut core::ffi::c_int,
    ) -> lua_Number;
}
unsafe extern "C" {
    pub fn lua_tointegerx(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        isnum: *mut core::ffi::c_int,
    ) -> lua_Integer;
}
unsafe extern "C" {
    pub fn lua_toboolean(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_tolstring(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        len: *mut usize,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_rawlen(L: *mut lua_State, idx: core::ffi::c_int) -> lua_Unsigned;
}
unsafe extern "C" {
    pub fn lua_tocfunction(L: *mut lua_State, idx: core::ffi::c_int) -> lua_CFunction;
}
unsafe extern "C" {
    pub fn lua_touserdata(L: *mut lua_State, idx: core::ffi::c_int) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn lua_tothread(L: *mut lua_State, idx: core::ffi::c_int) -> *mut lua_State;
}
unsafe extern "C" {
    pub fn lua_topointer(L: *mut lua_State, idx: core::ffi::c_int) -> *const core::ffi::c_void;
}
unsafe extern "C" {
    pub fn lua_arith(L: *mut lua_State, op: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_rawequal(
        L: *mut lua_State,
        idx1: core::ffi::c_int,
        idx2: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_compare(
        L: *mut lua_State,
        idx1: core::ffi::c_int,
        idx2: core::ffi::c_int,
        op: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_pushnil(L: *mut lua_State);
}
unsafe extern "C" {
    pub fn lua_pushnumber(L: *mut lua_State, n: lua_Number);
}
unsafe extern "C" {
    pub fn lua_pushinteger(L: *mut lua_State, n: lua_Integer);
}
unsafe extern "C" {
    pub fn lua_pushlstring(
        L: *mut lua_State,
        s: *const core::ffi::c_char,
        len: usize,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_pushexternalstring(
        L: *mut lua_State,
        s: *const core::ffi::c_char,
        len: usize,
        falloc: lua_Alloc,
        ud: *mut core::ffi::c_void,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_pushstring(
        L: *mut lua_State,
        s: *const core::ffi::c_char,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_pushfstring(
        L: *mut lua_State,
        fmt: *const core::ffi::c_char,
        ...
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_pushcclosure(L: *mut lua_State, fn_: lua_CFunction, n: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_pushboolean(L: *mut lua_State, b: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_pushlightuserdata(L: *mut lua_State, p: *mut core::ffi::c_void);
}
unsafe extern "C" {
    pub fn lua_pushthread(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_getglobal(L: *mut lua_State, name: *const core::ffi::c_char) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_gettable(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_getfield(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        k: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_geti(L: *mut lua_State, idx: core::ffi::c_int, n: lua_Integer) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_rawget(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_rawgeti(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        n: lua_Integer,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_rawgetp(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        p: *const core::ffi::c_void,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_createtable(L: *mut lua_State, narr: core::ffi::c_int, nrec: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_newuserdatauv(
        L: *mut lua_State,
        sz: usize,
        nuvalue: core::ffi::c_int,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn lua_getmetatable(L: *mut lua_State, objindex: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_getiuservalue(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        n: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_setglobal(L: *mut lua_State, name: *const core::ffi::c_char);
}
unsafe extern "C" {
    pub fn lua_settable(L: *mut lua_State, idx: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_setfield(L: *mut lua_State, idx: core::ffi::c_int, k: *const core::ffi::c_char);
}
unsafe extern "C" {
    pub fn lua_seti(L: *mut lua_State, idx: core::ffi::c_int, n: lua_Integer);
}
unsafe extern "C" {
    pub fn lua_rawset(L: *mut lua_State, idx: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_rawseti(L: *mut lua_State, idx: core::ffi::c_int, n: lua_Integer);
}
unsafe extern "C" {
    pub fn lua_rawsetp(L: *mut lua_State, idx: core::ffi::c_int, p: *const core::ffi::c_void);
}
unsafe extern "C" {
    pub fn lua_setmetatable(L: *mut lua_State, objindex: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_setiuservalue(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        n: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_callk(
        L: *mut lua_State,
        nargs: core::ffi::c_int,
        nresults: core::ffi::c_int,
        ctx: lua_KContext,
        k: lua_KFunction,
    );
}
unsafe extern "C" {
    pub fn lua_pcallk(
        L: *mut lua_State,
        nargs: core::ffi::c_int,
        nresults: core::ffi::c_int,
        errfunc: core::ffi::c_int,
        ctx: lua_KContext,
        k: lua_KFunction,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_load(
        L: *mut lua_State,
        reader: lua_Reader,
        dt: *mut core::ffi::c_void,
        chunkname: *const core::ffi::c_char,
        mode: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_dump(
        L: *mut lua_State,
        writer: lua_Writer,
        data: *mut core::ffi::c_void,
        strip: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_yieldk(
        L: *mut lua_State,
        nresults: core::ffi::c_int,
        ctx: lua_KContext,
        k: lua_KFunction,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_resume(
        L: *mut lua_State,
        from: *mut lua_State,
        narg: core::ffi::c_int,
        nres: *mut core::ffi::c_int,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_status(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_isyieldable(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_setwarnf(L: *mut lua_State, f: lua_WarnFunction, ud: *mut core::ffi::c_void);
}
unsafe extern "C" {
    pub fn lua_warning(L: *mut lua_State, msg: *const core::ffi::c_char, tocont: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_gc(L: *mut lua_State, what: core::ffi::c_int, ...) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_error(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_next(L: *mut lua_State, idx: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_concat(L: *mut lua_State, n: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_len(L: *mut lua_State, idx: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_numbertocstring(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        buff: *mut core::ffi::c_char,
    ) -> core::ffi::c_uint;
}
unsafe extern "C" {
    pub fn lua_stringtonumber(L: *mut lua_State, s: *const core::ffi::c_char) -> usize;
}
unsafe extern "C" {
    pub fn lua_getallocf(L: *mut lua_State, ud: *mut *mut core::ffi::c_void) -> lua_Alloc;
}
unsafe extern "C" {
    pub fn lua_setallocf(L: *mut lua_State, f: lua_Alloc, ud: *mut core::ffi::c_void);
}
unsafe extern "C" {
    pub fn lua_toclose(L: *mut lua_State, idx: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_closeslot(L: *mut lua_State, idx: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn lua_getstack(
        L: *mut lua_State,
        level: core::ffi::c_int,
        ar: *mut lua_Debug,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_getinfo(
        L: *mut lua_State,
        what: *const core::ffi::c_char,
        ar: *mut lua_Debug,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_getlocal(
        L: *mut lua_State,
        ar: *const lua_Debug,
        n: core::ffi::c_int,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_setlocal(
        L: *mut lua_State,
        ar: *const lua_Debug,
        n: core::ffi::c_int,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_getupvalue(
        L: *mut lua_State,
        funcindex: core::ffi::c_int,
        n: core::ffi::c_int,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_setupvalue(
        L: *mut lua_State,
        funcindex: core::ffi::c_int,
        n: core::ffi::c_int,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn lua_upvalueid(
        L: *mut lua_State,
        fidx: core::ffi::c_int,
        n: core::ffi::c_int,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn lua_upvaluejoin(
        L: *mut lua_State,
        fidx1: core::ffi::c_int,
        n1: core::ffi::c_int,
        fidx2: core::ffi::c_int,
        n2: core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn lua_sethook(
        L: *mut lua_State,
        func: lua_Hook,
        mask: core::ffi::c_int,
        count: core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn lua_gethook(L: *mut lua_State) -> lua_Hook;
}
unsafe extern "C" {
    pub fn lua_gethookmask(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn lua_gethookcount(L: *mut lua_State) -> core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_Debug {
    pub event: core::ffi::c_int,
    pub name: *const core::ffi::c_char,
    pub namewhat: *const core::ffi::c_char,
    pub what: *const core::ffi::c_char,
    pub source: *const core::ffi::c_char,
    pub srclen: usize,
    pub currentline: core::ffi::c_int,
    pub linedefined: core::ffi::c_int,
    pub lastlinedefined: core::ffi::c_int,
    pub nups: core::ffi::c_uchar,
    pub nparams: core::ffi::c_uchar,
    pub isvararg: core::ffi::c_char,
    pub extraargs: core::ffi::c_uchar,
    pub istailcall: core::ffi::c_char,
    pub ftransfer: core::ffi::c_int,
    pub ntransfer: core::ffi::c_int,
    pub short_src: [core::ffi::c_char; 60usize],
    pub i_ci: *mut CallInfo,
}
impl Default for lua_Debug {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct luaL_Reg {
    pub name: *const core::ffi::c_char,
    pub func: lua_CFunction,
}
impl Default for luaL_Reg {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn luaL_checkversion_(L: *mut lua_State, ver: lua_Number, sz: usize);
}
unsafe extern "C" {
    pub fn luaL_getmetafield(
        L: *mut lua_State,
        obj: core::ffi::c_int,
        e: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_callmeta(
        L: *mut lua_State,
        obj: core::ffi::c_int,
        e: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_tolstring(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        len: *mut usize,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn luaL_argerror(
        L: *mut lua_State,
        arg: core::ffi::c_int,
        extramsg: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_typeerror(
        L: *mut lua_State,
        arg: core::ffi::c_int,
        tname: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_checklstring(
        L: *mut lua_State,
        arg: core::ffi::c_int,
        l: *mut usize,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn luaL_optlstring(
        L: *mut lua_State,
        arg: core::ffi::c_int,
        def: *const core::ffi::c_char,
        l: *mut usize,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn luaL_checknumber(L: *mut lua_State, arg: core::ffi::c_int) -> lua_Number;
}
unsafe extern "C" {
    pub fn luaL_optnumber(L: *mut lua_State, arg: core::ffi::c_int, def: lua_Number) -> lua_Number;
}
unsafe extern "C" {
    pub fn luaL_checkinteger(L: *mut lua_State, arg: core::ffi::c_int) -> lua_Integer;
}
unsafe extern "C" {
    pub fn luaL_optinteger(
        L: *mut lua_State,
        arg: core::ffi::c_int,
        def: lua_Integer,
    ) -> lua_Integer;
}
unsafe extern "C" {
    pub fn luaL_checkstack(L: *mut lua_State, sz: core::ffi::c_int, msg: *const core::ffi::c_char);
}
unsafe extern "C" {
    pub fn luaL_checktype(L: *mut lua_State, arg: core::ffi::c_int, t: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn luaL_checkany(L: *mut lua_State, arg: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn luaL_newmetatable(
        L: *mut lua_State,
        tname: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_setmetatable(L: *mut lua_State, tname: *const core::ffi::c_char);
}
unsafe extern "C" {
    pub fn luaL_testudata(
        L: *mut lua_State,
        ud: core::ffi::c_int,
        tname: *const core::ffi::c_char,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn luaL_checkudata(
        L: *mut lua_State,
        ud: core::ffi::c_int,
        tname: *const core::ffi::c_char,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn luaL_where(L: *mut lua_State, lvl: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn luaL_error(L: *mut lua_State, fmt: *const core::ffi::c_char, ...) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_checkoption(
        L: *mut lua_State,
        arg: core::ffi::c_int,
        def: *const core::ffi::c_char,
        lst: *const *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_fileresult(
        L: *mut lua_State,
        stat: core::ffi::c_int,
        fname: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_execresult(L: *mut lua_State, stat: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_alloc(
        ud: *mut core::ffi::c_void,
        ptr: *mut core::ffi::c_void,
        osize: usize,
        nsize: usize,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    pub fn luaL_ref(L: *mut lua_State, t: core::ffi::c_int) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_unref(L: *mut lua_State, t: core::ffi::c_int, ref_: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn luaL_loadfilex(
        L: *mut lua_State,
        filename: *const core::ffi::c_char,
        mode: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_loadbufferx(
        L: *mut lua_State,
        buff: *const core::ffi::c_char,
        sz: usize,
        name: *const core::ffi::c_char,
        mode: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_loadstring(L: *mut lua_State, s: *const core::ffi::c_char) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_newstate() -> *mut lua_State;
}
unsafe extern "C" {
    pub fn luaL_makeseed(L: *mut lua_State) -> core::ffi::c_uint;
}
unsafe extern "C" {
    pub fn luaL_len(L: *mut lua_State, idx: core::ffi::c_int) -> lua_Integer;
}
unsafe extern "C" {
    pub fn luaL_addgsub(
        b: *mut luaL_Buffer,
        s: *const core::ffi::c_char,
        p: *const core::ffi::c_char,
        r: *const core::ffi::c_char,
    );
}
unsafe extern "C" {
    pub fn luaL_gsub(
        L: *mut lua_State,
        s: *const core::ffi::c_char,
        p: *const core::ffi::c_char,
        r: *const core::ffi::c_char,
    ) -> *const core::ffi::c_char;
}
unsafe extern "C" {
    pub fn luaL_setfuncs(L: *mut lua_State, l: *const luaL_Reg, nup: core::ffi::c_int);
}
unsafe extern "C" {
    pub fn luaL_getsubtable(
        L: *mut lua_State,
        idx: core::ffi::c_int,
        fname: *const core::ffi::c_char,
    ) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_traceback(
        L: *mut lua_State,
        L1: *mut lua_State,
        msg: *const core::ffi::c_char,
        level: core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn luaL_requiref(
        L: *mut lua_State,
        modname: *const core::ffi::c_char,
        openf: lua_CFunction,
        glb: core::ffi::c_int,
    );
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct luaL_Buffer {
    pub b: *mut core::ffi::c_char,
    pub size: usize,
    pub n: usize,
    pub L: *mut lua_State,
    pub init: luaL_Buffer__bindgen_ty_1,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union luaL_Buffer__bindgen_ty_1 {
    pub u: u128,
    pub s: *mut core::ffi::c_void,
    pub l: core::ffi::c_longlong,
    pub b: [core::ffi::c_char; 1024usize],
}
impl Default for luaL_Buffer__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for luaL_Buffer {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn luaL_buffinit(L: *mut lua_State, B: *mut luaL_Buffer);
}
unsafe extern "C" {
    pub fn luaL_prepbuffsize(B: *mut luaL_Buffer, sz: usize) -> *mut core::ffi::c_char;
}
unsafe extern "C" {
    pub fn luaL_addlstring(B: *mut luaL_Buffer, s: *const core::ffi::c_char, l: usize);
}
unsafe extern "C" {
    pub fn luaL_addstring(B: *mut luaL_Buffer, s: *const core::ffi::c_char);
}
unsafe extern "C" {
    pub fn luaL_addvalue(B: *mut luaL_Buffer);
}
unsafe extern "C" {
    pub fn luaL_pushresult(B: *mut luaL_Buffer);
}
unsafe extern "C" {
    pub fn luaL_pushresultsize(B: *mut luaL_Buffer, sz: usize);
}
unsafe extern "C" {
    pub fn luaL_buffinitsize(
        L: *mut lua_State,
        B: *mut luaL_Buffer,
        sz: usize,
    ) -> *mut core::ffi::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct luaL_Stream {
    pub f: *mut FILE,
    pub closef: lua_CFunction,
}
impl Default for luaL_Stream {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn luaopen_base(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_package(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_coroutine(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_debug(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_io(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_math(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_os(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_string(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_table(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaopen_utf8(L: *mut lua_State) -> core::ffi::c_int;
}
unsafe extern "C" {
    pub fn luaL_openselectedlibs(
        L: *mut lua_State,
        load: core::ffi::c_int,
        preload: core::ffi::c_int,
    );
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CallInfo {
    pub _address: u8,
}
