//! Raw FFI bindings to Lua 5.5.
//!
//! The contents are generated by bindgen from the vendored Lua headers and
//! committed to the repository; see `src/bin/regenerate.rs`.
//!
//! Unlike QuickJS, Lua has no `static inline` functions, so there is no C
//! shim. What bindgen cannot translate are the function-like macros
//! (`lua_pop`, `lua_pcall`, `lua_tostring`, ...) and the constants defined
//! through `sizeof` or other macros (`LUA_REGISTRYINDEX`, `LUAL_BUFFERSIZE`);
//! those are written out by hand at the bottom of this file.
//!
//! # Errors unwind with `longjmp`
//!
//! A Lua error (`lua_error`, `luaL_error`, any `luaL_check*` failure, running
//! out of memory, ...) jumps straight to the nearest protected call. Jumping
//! over Rust frames is undefined behavior whenever they have anything to drop,
//! so a `lua_CFunction` written in Rust must not hold values with destructors
//! across a call that can raise, and must never let a Rust panic escape.

#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::all)]

// LUAL_BUFFERSIZE (and so the size of luaL_Buffer in the committed bindings)
// depends on the pointer width.
#[cfg(not(target_pointer_width = "64"))]
compile_error!("karna-lua-sys only supports 64-bit targets");

use core::ffi::c_char;
use core::ffi::c_int;
use core::ffi::c_void;
use core::mem::size_of;
use core::ptr;

include!("bindings.rs");

/// C's `FILE`, only ever handled by pointer (see `luaL_Stream`).
#[repr(C)]
pub struct FILE {
    _unused: [u8; 0],
}

pub const LUA_REGISTRYINDEX: c_int = -(c_int::MAX / 2 + 1000);
pub const LUA_EXTRASPACE: usize = size_of::<*mut c_void>();
pub const LUAL_BUFFERSIZE: c_int = (16 * size_of::<*mut c_void>() * size_of::<lua_Number>()) as c_int;
pub const LUAL_NUMSIZES: usize = size_of::<lua_Integer>() * 16 + size_of::<lua_Number>();

#[inline]
pub const fn lua_upvalueindex(i: c_int) -> c_int {
    LUA_REGISTRYINDEX - i
}

// lua.h

#[inline]
pub unsafe fn lua_call(L: *mut lua_State, n: c_int, r: c_int) {
    unsafe { lua_callk(L, n, r, 0, None) }
}

#[inline]
pub unsafe fn lua_pcall(L: *mut lua_State, n: c_int, r: c_int, f: c_int) -> c_int {
    unsafe { lua_pcallk(L, n, r, f, 0, None) }
}

#[inline]
pub unsafe fn lua_yield(L: *mut lua_State, n: c_int) -> c_int {
    unsafe { lua_yieldk(L, n, 0, None) }
}

#[inline]
pub unsafe fn lua_getextraspace(L: *mut lua_State) -> *mut c_void {
    unsafe { L.cast::<u8>().sub(LUA_EXTRASPACE).cast() }
}

#[inline]
pub unsafe fn lua_tonumber(L: *mut lua_State, i: c_int) -> lua_Number {
    unsafe { lua_tonumberx(L, i, ptr::null_mut()) }
}

#[inline]
pub unsafe fn lua_tointeger(L: *mut lua_State, i: c_int) -> lua_Integer {
    unsafe { lua_tointegerx(L, i, ptr::null_mut()) }
}

#[inline]
pub unsafe fn lua_pop(L: *mut lua_State, n: c_int) {
    unsafe { lua_settop(L, -n - 1) }
}

#[inline]
pub unsafe fn lua_newtable(L: *mut lua_State) {
    unsafe { lua_createtable(L, 0, 0) }
}

#[inline]
pub unsafe fn lua_register(L: *mut lua_State, n: *const c_char, f: lua_CFunction) {
    unsafe {
        lua_pushcfunction(L, f);
        lua_setglobal(L, n);
    }
}

#[inline]
pub unsafe fn lua_pushcfunction(L: *mut lua_State, f: lua_CFunction) {
    unsafe { lua_pushcclosure(L, f, 0) }
}

#[inline]
pub unsafe fn lua_isfunction(L: *mut lua_State, n: c_int) -> bool {
    unsafe { lua_type(L, n) == LUA_TFUNCTION }
}

#[inline]
pub unsafe fn lua_istable(L: *mut lua_State, n: c_int) -> bool {
    unsafe { lua_type(L, n) == LUA_TTABLE }
}

#[inline]
pub unsafe fn lua_islightuserdata(L: *mut lua_State, n: c_int) -> bool {
    unsafe { lua_type(L, n) == LUA_TLIGHTUSERDATA }
}

#[inline]
pub unsafe fn lua_isnil(L: *mut lua_State, n: c_int) -> bool {
    unsafe { lua_type(L, n) == LUA_TNIL }
}

#[inline]
pub unsafe fn lua_isboolean(L: *mut lua_State, n: c_int) -> bool {
    unsafe { lua_type(L, n) == LUA_TBOOLEAN }
}

#[inline]
pub unsafe fn lua_isthread(L: *mut lua_State, n: c_int) -> bool {
    unsafe { lua_type(L, n) == LUA_TTHREAD }
}

#[inline]
pub unsafe fn lua_isnone(L: *mut lua_State, n: c_int) -> bool {
    unsafe { lua_type(L, n) == LUA_TNONE }
}

#[inline]
pub unsafe fn lua_isnoneornil(L: *mut lua_State, n: c_int) -> bool {
    unsafe { lua_type(L, n) <= 0 }
}

/// `lua_pushliteral` is only `lua_pushstring` with a compile-time string.
#[inline]
pub unsafe fn lua_pushliteral(L: *mut lua_State, s: &core::ffi::CStr) -> *const c_char {
    unsafe { lua_pushstring(L, s.as_ptr()) }
}

#[inline]
pub unsafe fn lua_pushglobaltable(L: *mut lua_State) {
    unsafe {
        lua_rawgeti(L, LUA_REGISTRYINDEX, LUA_RIDX_GLOBALS as lua_Integer);
    }
}

#[inline]
pub unsafe fn lua_tostring(L: *mut lua_State, i: c_int) -> *const c_char {
    unsafe { lua_tolstring(L, i, ptr::null_mut()) }
}

#[inline]
pub unsafe fn lua_insert(L: *mut lua_State, idx: c_int) {
    unsafe { lua_rotate(L, idx, 1) }
}

#[inline]
pub unsafe fn lua_remove(L: *mut lua_State, idx: c_int) {
    unsafe {
        lua_rotate(L, idx, -1);
        lua_pop(L, 1);
    }
}

#[inline]
pub unsafe fn lua_replace(L: *mut lua_State, idx: c_int) {
    unsafe {
        lua_copy(L, -1, idx);
        lua_pop(L, 1);
    }
}

#[inline]
pub unsafe fn lua_newuserdata(L: *mut lua_State, s: usize) -> *mut c_void {
    unsafe { lua_newuserdatauv(L, s, 1) }
}

#[inline]
pub unsafe fn lua_getuservalue(L: *mut lua_State, idx: c_int) -> c_int {
    unsafe { lua_getiuservalue(L, idx, 1) }
}

#[inline]
pub unsafe fn lua_setuservalue(L: *mut lua_State, idx: c_int) -> c_int {
    unsafe { lua_setiuservalue(L, idx, 1) }
}

#[inline]
pub unsafe fn lua_resetthread(L: *mut lua_State) -> c_int {
    unsafe { lua_closethread(L, ptr::null_mut()) }
}

// lualib.h

#[inline]
pub unsafe fn luaL_openlibs(L: *mut lua_State) {
    unsafe { luaL_openselectedlibs(L, !0, 0) }
}

// lauxlib.h

#[inline]
pub unsafe fn luaL_checkversion(L: *mut lua_State) {
    unsafe { luaL_checkversion_(L, LUA_VERSION_NUM as lua_Number, LUAL_NUMSIZES) }
}

#[inline]
pub unsafe fn luaL_loadfile(L: *mut lua_State, f: *const c_char) -> c_int {
    unsafe { luaL_loadfilex(L, f, ptr::null()) }
}

/// `l` must end with the `{NULL, NULL}` sentinel, as in C.
#[inline]
pub unsafe fn luaL_newlibtable(L: *mut lua_State, l: &[luaL_Reg]) {
    unsafe { lua_createtable(L, 0, l.len() as c_int - 1) }
}

/// `l` must end with the `{NULL, NULL}` sentinel, as in C.
#[inline]
pub unsafe fn luaL_newlib(L: *mut lua_State, l: &[luaL_Reg]) {
    unsafe {
        luaL_checkversion(L);
        luaL_newlibtable(L, l);
        luaL_setfuncs(L, l.as_ptr(), 0);
    }
}

#[inline]
pub unsafe fn luaL_argcheck(L: *mut lua_State, cond: bool, arg: c_int, extramsg: *const c_char) {
    if !cond {
        unsafe { luaL_argerror(L, arg, extramsg) };
    }
}

#[inline]
pub unsafe fn luaL_argexpected(L: *mut lua_State, cond: bool, arg: c_int, tname: *const c_char) {
    if !cond {
        unsafe { luaL_typeerror(L, arg, tname) };
    }
}

#[inline]
pub unsafe fn luaL_checkstring(L: *mut lua_State, n: c_int) -> *const c_char {
    unsafe { luaL_checklstring(L, n, ptr::null_mut()) }
}

#[inline]
pub unsafe fn luaL_optstring(L: *mut lua_State, n: c_int, d: *const c_char) -> *const c_char {
    unsafe { luaL_optlstring(L, n, d, ptr::null_mut()) }
}

#[inline]
pub unsafe fn luaL_typename(L: *mut lua_State, i: c_int) -> *const c_char {
    unsafe { lua_typename(L, lua_type(L, i)) }
}

#[inline]
pub unsafe fn luaL_dofile(L: *mut lua_State, f: *const c_char) -> c_int {
    unsafe {
        match luaL_loadfile(L, f) {
            LUA_OK => lua_pcall(L, 0, LUA_MULTRET, 0),
            status => status,
        }
    }
}

#[inline]
pub unsafe fn luaL_dostring(L: *mut lua_State, s: *const c_char) -> c_int {
    unsafe {
        match luaL_loadstring(L, s) {
            LUA_OK => lua_pcall(L, 0, LUA_MULTRET, 0),
            status => status,
        }
    }
}

#[inline]
pub unsafe fn luaL_getmetatable(L: *mut lua_State, n: *const c_char) -> c_int {
    unsafe { lua_getfield(L, LUA_REGISTRYINDEX, n) }
}

#[inline]
pub unsafe fn luaL_loadbuffer(
    L: *mut lua_State,
    s: *const c_char,
    sz: usize,
    n: *const c_char,
) -> c_int {
    unsafe { luaL_loadbufferx(L, s, sz, n, ptr::null()) }
}

/// Matches the default build, where LUA_FAILISFALSE is not defined.
#[inline]
pub unsafe fn luaL_pushfail(L: *mut lua_State) {
    unsafe { lua_pushnil(L) }
}

#[inline]
pub unsafe fn luaL_bufflen(bf: *const luaL_Buffer) -> usize {
    unsafe { (*bf).n }
}

#[inline]
pub unsafe fn luaL_buffaddr(bf: *const luaL_Buffer) -> *mut c_char {
    unsafe { (*bf).b }
}

#[inline]
pub unsafe fn luaL_addchar(B: *mut luaL_Buffer, c: c_char) {
    unsafe {
        if (*B).n >= (*B).size {
            luaL_prepbuffsize(B, 1);
        }
        *(*B).b.add((*B).n) = c;
        (*B).n += 1;
    }
}

#[inline]
pub unsafe fn luaL_addsize(B: *mut luaL_Buffer, s: usize) {
    unsafe { (*B).n += s }
}

#[inline]
pub unsafe fn luaL_buffsub(B: *mut luaL_Buffer, s: usize) {
    unsafe { (*B).n -= s }
}

#[inline]
pub unsafe fn luaL_prepbuffer(B: *mut luaL_Buffer) -> *mut c_char {
    unsafe { luaL_prepbuffsize(B, LUAL_BUFFERSIZE as usize) }
}
