//! Raw FFI bindings to QuickJS (the quickjs-ng fork).
//!
//! The contents are generated by bindgen from the vendored QuickJS headers and
//! committed to the repository; see `src/bin/regenerate.rs`.
//!
//! quickjs.h implements part of its API as `static inline` functions
//! (`JS_NewInt32`, `JS_IsException`, `JS_ToCString`, `JS_NewCFunction`, ...).
//! Those are reached through `src/extern.c`, a bindgen-generated shim that
//! build.rs compiles, so they are called exactly like the exported ones.
//!
//! What bindgen cannot translate at all are the function-like macros; the
//! commonly needed ones (`JS_UNDEFINED`, `JS_VALUE_GET_TAG`, ...) are written
//! out by hand at the bottom of this file.

#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::all)]

// The committed bindings use the 64-bit JSValue layout (a tagged struct).
// 32-bit targets NaN-box JSValue into a u64 instead, which would need its own
// set of bindings.
#[cfg(not(target_pointer_width = "64"))]
compile_error!("karna-quickjs-sys only supports 64-bit targets");

include!("bindings.rs");

/// C's `FILE`, only ever handled by pointer (see `JS_DumpMemoryUsage`).
#[repr(C)]
pub struct FILE {
    _unused: [u8; 0],
}

const fn mkval(tag: core::ffi::c_int, int32: i32) -> JSValue {
    JSValue {
        u: JSValueUnion { int32 },
        tag: tag as i64,
    }
}

pub const JS_NULL: JSValue = mkval(JS_TAG_NULL, 0);
pub const JS_UNDEFINED: JSValue = mkval(JS_TAG_UNDEFINED, 0);
pub const JS_FALSE: JSValue = mkval(JS_TAG_BOOL, 0);
pub const JS_TRUE: JSValue = mkval(JS_TAG_BOOL, 1);
pub const JS_EXCEPTION: JSValue = mkval(JS_TAG_EXCEPTION, 0);
pub const JS_UNINITIALIZED: JSValue = mkval(JS_TAG_UNINITIALIZED, 0);

#[inline]
pub const fn JS_MKVAL(tag: core::ffi::c_int, val: i32) -> JSValue {
    mkval(tag, val)
}

#[inline]
pub const fn JS_MKPTR(tag: core::ffi::c_int, ptr: *mut core::ffi::c_void) -> JSValue {
    JSValue {
        u: JSValueUnion { ptr },
        tag: tag as i64,
    }
}

#[inline]
pub const fn JS_VALUE_GET_TAG(v: JSValue) -> i32 {
    v.tag as i32
}

/// Same as [`JS_VALUE_GET_TAG`]; they only differ on NaN-boxed targets.
#[inline]
pub const fn JS_VALUE_GET_NORM_TAG(v: JSValue) -> i32 {
    JS_VALUE_GET_TAG(v)
}

/// # Safety
/// `v` must hold an int (`JS_TAG_INT`).
#[inline]
pub const unsafe fn JS_VALUE_GET_INT(v: JSValue) -> i32 {
    unsafe { v.u.int32 }
}

/// # Safety
/// `v` must hold a bool (`JS_TAG_BOOL`).
#[inline]
pub const unsafe fn JS_VALUE_GET_BOOL(v: JSValue) -> i32 {
    unsafe { v.u.int32 }
}

/// # Safety
/// `v` must hold a float (`JS_TAG_FLOAT64`).
#[inline]
pub const unsafe fn JS_VALUE_GET_FLOAT64(v: JSValue) -> f64 {
    unsafe { v.u.float64 }
}

/// # Safety
/// `v` must hold a pointer (a tag with a reference count, see
/// [`JS_VALUE_HAS_REF_COUNT`]).
#[inline]
pub const unsafe fn JS_VALUE_GET_PTR(v: JSValue) -> *mut core::ffi::c_void {
    unsafe { v.u.ptr }
}

#[inline]
pub const fn JS_TAG_IS_FLOAT64(tag: i32) -> bool {
    tag as u32 == JS_TAG_FLOAT64 as u32
}

#[inline]
pub const fn JS_VALUE_HAS_REF_COUNT(v: JSValue) -> bool {
    JS_VALUE_GET_TAG(v) as u32 >= JS_TAG_FIRST as u32
}
