pub const IMMEDIATE_VERTEX_BASE_CAPACITY: usize = 4096;
pub const IMMEDIATE_INDEX_BASE_CAPACITY: usize = IMMEDIATE_VERTEX_BASE_CAPACITY * 2;
pub const MESH_INSTANCE_BASE_CAPACITY: usize = 1024;
pub const TEXT_INSTANCE_BASE_CAPACITY: usize = 1024;

pub const TEXTURE_ATLAS_BASE_SIZE: (u32, u32) = (1024, 1024);
