use imgui::Key as IK;
use imgui::MouseButton as IM;
use winit::event::MouseButton as WM;
use winit::keyboard::KeyCode as WK;

pub fn winit_mousebutton_to_imgui(button: &WM) -> Option<IM> {
    match button {
        WM::Left | WM::Other(0) => Some(IM::Left),
        WM::Right | WM::Other(1) => Some(IM::Right),
        WM::Middle | WM::Other(2) => Some(IM::Middle),
        WM::Other(3) => Some(IM::Extra1),
        WM::Other(4) => Some(IM::Extra2),
        _ => None,
    }
}

pub fn winit_keycode_to_imgui(code: WK) -> Option<IK> {
    match code {
        WK::Tab => Some(IK::Tab),
        WK::ArrowLeft => Some(IK::LeftArrow),
        WK::ArrowUp => Some(IK::UpArrow),
        WK::ArrowRight => Some(IK::RightArrow),
        WK::ArrowDown => Some(IK::DownArrow),
        WK::PageUp => Some(IK::PageUp),
        WK::PageDown => Some(IK::PageDown),
        WK::Home => Some(IK::Home),
        WK::End => Some(IK::End),
        WK::Insert => Some(IK::Insert),
        WK::Delete => Some(IK::Delete),
        WK::Backspace => Some(IK::Backspace),
        WK::Space => Some(IK::Space),
        WK::Enter => Some(IK::Enter),
        WK::NumpadEnter => Some(IK::KeypadEnter),
        WK::Escape => Some(IK::Escape),
        WK::ControlLeft => Some(IK::LeftCtrl),
        WK::ControlRight => Some(IK::RightCtrl),
        WK::ShiftLeft => Some(IK::LeftShift),
        WK::ShiftRight => Some(IK::RightShift),
        WK::AltLeft => Some(IK::LeftAlt),
        WK::AltRight => Some(IK::RightAlt),
        WK::SuperLeft => Some(IK::LeftSuper),
        WK::SuperRight => Some(IK::RightSuper),
        WK::ContextMenu => Some(IK::Menu),

        WK::F1 => Some(IK::F1),
        WK::F2 => Some(IK::F2),
        WK::F3 => Some(IK::F3),
        WK::F4 => Some(IK::F4),
        WK::F5 => Some(IK::F5),
        WK::F6 => Some(IK::F6),
        WK::F7 => Some(IK::F7),
        WK::F8 => Some(IK::F8),
        WK::F9 => Some(IK::F9),
        WK::F10 => Some(IK::F10),
        WK::F11 => Some(IK::F11),
        WK::F12 => Some(IK::F12),

        WK::CapsLock => Some(IK::CapsLock),
        WK::ScrollLock => Some(IK::ScrollLock),
        WK::NumLock => Some(IK::NumLock),
        WK::PrintScreen => Some(IK::PrintScreen),
        WK::Pause => Some(IK::Pause),

        WK::Digit0 => Some(IK::Alpha0),
        WK::Digit1 => Some(IK::Alpha1),
        WK::Digit2 => Some(IK::Alpha2),
        WK::Digit3 => Some(IK::Alpha3),
        WK::Digit4 => Some(IK::Alpha4),
        WK::Digit5 => Some(IK::Alpha5),
        WK::Digit6 => Some(IK::Alpha6),
        WK::Digit7 => Some(IK::Alpha7),
        WK::Digit8 => Some(IK::Alpha8),
        WK::Digit9 => Some(IK::Alpha9),

        WK::Numpad0 => Some(IK::Keypad0),
        WK::Numpad1 => Some(IK::Keypad1),
        WK::Numpad2 => Some(IK::Keypad2),
        WK::Numpad3 => Some(IK::Keypad3),
        WK::Numpad4 => Some(IK::Keypad4),
        WK::Numpad5 => Some(IK::Keypad5),
        WK::Numpad6 => Some(IK::Keypad6),
        WK::Numpad7 => Some(IK::Keypad7),
        WK::Numpad8 => Some(IK::Keypad8),
        WK::Numpad9 => Some(IK::Keypad9),
        WK::NumpadDecimal => Some(IK::KeypadDecimal),
        WK::NumpadDivide => Some(IK::KeypadDivide),
        WK::NumpadMultiply => Some(IK::KeypadMultiply),
        WK::NumpadSubtract => Some(IK::KeypadSubtract),
        WK::NumpadAdd => Some(IK::KeypadAdd),
        WK::NumpadEqual => Some(IK::KeypadEqual),

        WK::KeyA => Some(IK::A),
        WK::KeyB => Some(IK::B),
        WK::KeyC => Some(IK::C),
        WK::KeyD => Some(IK::D),
        WK::KeyE => Some(IK::E),
        WK::KeyF => Some(IK::F),
        WK::KeyG => Some(IK::G),
        WK::KeyH => Some(IK::H),
        WK::KeyI => Some(IK::I),
        WK::KeyJ => Some(IK::J),
        WK::KeyK => Some(IK::K),
        WK::KeyL => Some(IK::L),
        WK::KeyM => Some(IK::M),
        WK::KeyN => Some(IK::N),
        WK::KeyO => Some(IK::O),
        WK::KeyP => Some(IK::P),
        WK::KeyQ => Some(IK::Q),
        WK::KeyR => Some(IK::R),
        WK::KeyS => Some(IK::S),
        WK::KeyT => Some(IK::T),
        WK::KeyU => Some(IK::U),
        WK::KeyV => Some(IK::V),
        WK::KeyW => Some(IK::W),
        WK::KeyX => Some(IK::X),
        WK::KeyY => Some(IK::Y),
        WK::KeyZ => Some(IK::Z),

        WK::Quote => Some(IK::Apostrophe),
        WK::Comma => Some(IK::Comma),
        WK::Minus => Some(IK::Minus),
        WK::Period => Some(IK::Period),
        WK::Slash => Some(IK::Slash),
        WK::Semicolon => Some(IK::Semicolon),
        WK::Equal => Some(IK::Equal),
        WK::BracketLeft => Some(IK::LeftBracket),
        WK::Backslash => Some(IK::Backslash),
        WK::BracketRight => Some(IK::RightBracket),
        WK::Backquote => Some(IK::GraveAccent),

        _ => None,
    }
}
