use dear_imgui_rs::Key as IK;
use dear_imgui_rs::MouseButton as IM;
use sdl3::keyboard::Scancode as SK;
use sdl3::mouse::MouseButton as SM;

pub fn sdl_mousebutton_to_imgui(button: SM) -> Option<IM> {
    match button {
        SM::Left => Some(IM::Left),
        SM::Right => Some(IM::Right),
        SM::Middle => Some(IM::Middle),
        SM::X1 => Some(IM::Extra1),
        SM::X2 => Some(IM::Extra2),
        _ => None,
    }
}

/// Imgui tracks modifier state through dedicated mod keys, sent in addition
/// to the plain left/right key events.
pub fn sdl_scancode_to_imgui_mod(code: SK) -> Option<IK> {
    match code {
        SK::LCtrl | SK::RCtrl => Some(IK::ModCtrl),
        SK::LShift | SK::RShift => Some(IK::ModShift),
        SK::LAlt | SK::RAlt => Some(IK::ModAlt),
        SK::LGui | SK::RGui => Some(IK::ModSuper),
        _ => None,
    }
}

pub fn sdl_scancode_to_imgui(code: SK) -> Option<IK> {
    match code {
        SK::Tab => Some(IK::Tab),
        SK::Left => Some(IK::LeftArrow),
        SK::Up => Some(IK::UpArrow),
        SK::Right => Some(IK::RightArrow),
        SK::Down => Some(IK::DownArrow),
        SK::PageUp => Some(IK::PageUp),
        SK::PageDown => Some(IK::PageDown),
        SK::Home => Some(IK::Home),
        SK::End => Some(IK::End),
        SK::Insert => Some(IK::Insert),
        SK::Delete => Some(IK::Delete),
        SK::Backspace => Some(IK::Backspace),
        SK::Space => Some(IK::Space),
        SK::Return => Some(IK::Enter),
        SK::Return2 => Some(IK::KeypadEnter),
        SK::Escape => Some(IK::Escape),
        SK::LCtrl => Some(IK::LeftCtrl),
        SK::RCtrl => Some(IK::RightCtrl),
        SK::LShift => Some(IK::LeftShift),
        SK::RShift => Some(IK::RightShift),
        SK::LAlt => Some(IK::LeftAlt),
        SK::RAlt => Some(IK::RightAlt),
        SK::LGui => Some(IK::LeftSuper),
        SK::RGui => Some(IK::RightSuper),
        SK::Menu => Some(IK::Menu),

        SK::F1 => Some(IK::F1),
        SK::F2 => Some(IK::F2),
        SK::F3 => Some(IK::F3),
        SK::F4 => Some(IK::F4),
        SK::F5 => Some(IK::F5),
        SK::F6 => Some(IK::F6),
        SK::F7 => Some(IK::F7),
        SK::F8 => Some(IK::F8),
        SK::F9 => Some(IK::F9),
        SK::F10 => Some(IK::F10),
        SK::F11 => Some(IK::F11),
        SK::F12 => Some(IK::F12),

        SK::CapsLock => Some(IK::CapsLock),
        SK::ScrollLock => Some(IK::ScrollLock),
        SK::NumLockClear => Some(IK::NumLock),
        SK::PrintScreen => Some(IK::PrintScreen),
        SK::Pause => Some(IK::Pause),

        SK::_0 => Some(IK::Key0),
        SK::_1 => Some(IK::Key1),
        SK::_2 => Some(IK::Key2),
        SK::_3 => Some(IK::Key3),
        SK::_4 => Some(IK::Key4),
        SK::_5 => Some(IK::Key5),
        SK::_6 => Some(IK::Key6),
        SK::_7 => Some(IK::Key7),
        SK::_8 => Some(IK::Key8),
        SK::_9 => Some(IK::Key9),

        SK::Kp0 => Some(IK::Keypad0),
        SK::Kp1 => Some(IK::Keypad1),
        SK::Kp2 => Some(IK::Keypad2),
        SK::Kp3 => Some(IK::Keypad3),
        SK::Kp4 => Some(IK::Keypad4),
        SK::Kp5 => Some(IK::Keypad5),
        SK::Kp6 => Some(IK::Keypad6),
        SK::Kp7 => Some(IK::Keypad7),
        SK::Kp8 => Some(IK::Keypad8),
        SK::Kp9 => Some(IK::Keypad9),
        SK::KpDecimal => Some(IK::KeypadDecimal),
        SK::KpDivide => Some(IK::KeypadDivide),
        SK::KpMultiply => Some(IK::KeypadMultiply),
        SK::KpMinus => Some(IK::KeypadSubtract),
        SK::KpPlus => Some(IK::KeypadAdd),
        SK::KpEquals => Some(IK::KeypadEqual),

        SK::A => Some(IK::A),
        SK::B => Some(IK::B),
        SK::C => Some(IK::C),
        SK::D => Some(IK::D),
        SK::E => Some(IK::E),
        SK::F => Some(IK::F),
        SK::G => Some(IK::G),
        SK::H => Some(IK::H),
        SK::I => Some(IK::I),
        SK::J => Some(IK::J),
        SK::K => Some(IK::K),
        SK::L => Some(IK::L),
        SK::M => Some(IK::M),
        SK::N => Some(IK::N),
        SK::O => Some(IK::O),
        SK::P => Some(IK::P),
        SK::Q => Some(IK::Q),
        SK::R => Some(IK::R),
        SK::S => Some(IK::S),
        SK::T => Some(IK::T),
        SK::U => Some(IK::U),
        SK::V => Some(IK::V),
        SK::W => Some(IK::W),
        SK::X => Some(IK::X),
        SK::Y => Some(IK::Y),
        SK::Z => Some(IK::Z),

        SK::Apostrophe => Some(IK::Apostrophe),
        SK::Comma => Some(IK::Comma),
        SK::Minus => Some(IK::Minus),
        SK::Period => Some(IK::Period),
        SK::Slash => Some(IK::Slash),
        SK::Semicolon => Some(IK::Semicolon),
        SK::Equals => Some(IK::Equal),
        SK::LeftBracket => Some(IK::LeftBracket),
        SK::RightBracket => Some(IK::RightBracket),
        SK::Backslash => Some(IK::Backslash),
        SK::Grave => Some(IK::GraveAccent),

        _ => None,
    }
}
