[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
macros.workspace = true
utils.workspace = true
assets.workspace = true
math.workspace = true
wgpu.workspace = true
winit.workspace = true
gpu.workspace = true
logging.workspace = true
globals.workspace = true
fontdue.workspace = true
