[package]
name = "karna-js"
description = "JavaScript scripting for the karna engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "js"
path = "src/lib.rs"

[features]
default = ["build-from-source"]
build-from-source = [
    "karna-engine/build-from-source",
    "karna-quickjs/build-from-source",
    "karna-sdl3/build-from-source",
]

[dependencies]
karna-engine.workspace = true
karna-quickjs.workspace = true
karna-sdl3.workspace = true
karna-nostd.workspace = true
karna-math.workspace = true
traccia.workspace = true
