/* automatically generated by rust-bindgen 0.72.1 */

pub const SDL_SHADERCROSS_MAJOR_VERSION: u32 = 3;
pub const SDL_SHADERCROSS_MINOR_VERSION: u32 = 0;
pub const SDL_SHADERCROSS_MICRO_VERSION: u32 = 0;
pub const SDL_SHADERCROSS_PROP_SHADER_DEBUG_ENABLE_BOOLEAN: &[u8; 35] =
    b"SDL_shadercross.spirv.debug.enable\0";
pub const SDL_SHADERCROSS_PROP_SHADER_DEBUG_NAME_STRING: &[u8; 33] =
    b"SDL_shadercross.spirv.debug.name\0";
pub const SDL_SHADERCROSS_PROP_SHADER_CULL_UNUSED_BINDINGS_BOOLEAN: &[u8; 43] =
    b"SDL_shadercross.spirv.cull_unused_bindings\0";
pub const SDL_SHADERCROSS_PROP_SPIRV_PSSL_COMPATIBILITY_BOOLEAN: &[u8; 41] =
    b"SDL_shadercross.spirv.pssl.compatibility\0";
pub const SDL_SHADERCROSS_PROP_SPIRV_MSL_VERSION_STRING: &[u8; 34] =
    b"SDL_shadercross.spirv.msl.version\0";
pub const SDL_SHADERCROSS_PROP_HLSL_SKIP_SPIRV_ROUNDTRIP_BOOLEAN: &[u8; 42] =
    b"SDL_shadercross.hlsl.skip_spirv_roundtrip\0";
pub const SDL_SHADERCROSS_IOVAR_TYPE_UNKNOWN: SDL_ShaderCross_IOVarType = 0;
pub const SDL_SHADERCROSS_IOVAR_TYPE_INT8: SDL_ShaderCross_IOVarType = 1;
pub const SDL_SHADERCROSS_IOVAR_TYPE_UINT8: SDL_ShaderCross_IOVarType = 2;
pub const SDL_SHADERCROSS_IOVAR_TYPE_INT16: SDL_ShaderCross_IOVarType = 3;
pub const SDL_SHADERCROSS_IOVAR_TYPE_UINT16: SDL_ShaderCross_IOVarType = 4;
pub const SDL_SHADERCROSS_IOVAR_TYPE_INT32: SDL_ShaderCross_IOVarType = 5;
pub const SDL_SHADERCROSS_IOVAR_TYPE_UINT32: SDL_ShaderCross_IOVarType = 6;
pub const SDL_SHADERCROSS_IOVAR_TYPE_INT64: SDL_ShaderCross_IOVarType = 7;
pub const SDL_SHADERCROSS_IOVAR_TYPE_UINT64: SDL_ShaderCross_IOVarType = 8;
pub const SDL_SHADERCROSS_IOVAR_TYPE_FLOAT16: SDL_ShaderCross_IOVarType = 9;
pub const SDL_SHADERCROSS_IOVAR_TYPE_FLOAT32: SDL_ShaderCross_IOVarType = 10;
pub const SDL_SHADERCROSS_IOVAR_TYPE_FLOAT64: SDL_ShaderCross_IOVarType = 11;
pub type SDL_ShaderCross_IOVarType = core::ffi::c_uint;
pub const SDL_SHADERCROSS_SHADERSTAGE_VERTEX: SDL_ShaderCross_ShaderStage = 0;
pub const SDL_SHADERCROSS_SHADERSTAGE_FRAGMENT: SDL_ShaderCross_ShaderStage = 1;
pub const SDL_SHADERCROSS_SHADERSTAGE_COMPUTE: SDL_ShaderCross_ShaderStage = 2;
pub type SDL_ShaderCross_ShaderStage = core::ffi::c_uint;
#[repr(C)]
pub struct SDL_ShaderCross_IOVarMetadata {
    #[doc = "< The UTF-8 name of the variable."]
    pub name: *mut core::ffi::c_char,
    #[doc = "< The location of the variable."]
    pub location: Uint32,
    #[doc = "< The vector type of the variable."]
    pub vector_type: SDL_ShaderCross_IOVarType,
    #[doc = "< The number of components in the vector type of the variable."]
    pub vector_size: Uint32,
}
impl Default for SDL_ShaderCross_IOVarMetadata {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
pub struct SDL_ShaderCross_GraphicsShaderResourceInfo {
    #[doc = "< The number of samplers defined in the shader."]
    pub num_samplers: Uint32,
    #[doc = "< The number of storage textures defined in the shader."]
    pub num_storage_textures: Uint32,
    #[doc = "< The number of storage buffers defined in the shader."]
    pub num_storage_buffers: Uint32,
    #[doc = "< The number of uniform buffers defined in the shader."]
    pub num_uniform_buffers: Uint32,
}
impl Default for SDL_ShaderCross_GraphicsShaderResourceInfo {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
pub struct SDL_ShaderCross_GraphicsShaderMetadata {
    #[doc = "< Sub-struct containing the resource info of the shader."]
    pub resource_info: SDL_ShaderCross_GraphicsShaderResourceInfo,
    #[doc = "< The number of inputs defined in the shader."]
    pub num_inputs: Uint32,
    #[doc = "< The inputs defined in the shader."]
    pub inputs: *mut SDL_ShaderCross_IOVarMetadata,
    #[doc = "< The number of outputs defined in the shader."]
    pub num_outputs: Uint32,
    #[doc = "< The outputs defined in the shader."]
    pub outputs: *mut SDL_ShaderCross_IOVarMetadata,
}
impl Default for SDL_ShaderCross_GraphicsShaderMetadata {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
pub struct SDL_ShaderCross_ComputePipelineMetadata {
    #[doc = "< The number of samplers defined in the shader."]
    pub num_samplers: Uint32,
    #[doc = "< The number of readonly storage textures defined in the shader."]
    pub num_readonly_storage_textures: Uint32,
    #[doc = "< The number of readonly storage buffers defined in the shader."]
    pub num_readonly_storage_buffers: Uint32,
    #[doc = "< The number of read-write storage textures defined in the shader."]
    pub num_readwrite_storage_textures: Uint32,
    #[doc = "< The number of read-write storage buffers defined in the shader."]
    pub num_readwrite_storage_buffers: Uint32,
    #[doc = "< The number of uniform buffers defined in the shader."]
    pub num_uniform_buffers: Uint32,
    #[doc = "< The number of threads in the X dimension."]
    pub threadcount_x: Uint32,
    #[doc = "< The number of threads in the Y dimension."]
    pub threadcount_y: Uint32,
    #[doc = "< The number of threads in the Z dimension."]
    pub threadcount_z: Uint32,
}
impl Default for SDL_ShaderCross_ComputePipelineMetadata {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
pub struct SDL_ShaderCross_SPIRV_Info {
    #[doc = "< The SPIRV bytecode."]
    pub bytecode: *const Uint8,
    #[doc = "< The length of the SPIRV bytecode."]
    pub bytecode_size: usize,
    #[doc = "< The entry point function name for the shader in UTF-8."]
    pub entrypoint: *const core::ffi::c_char,
    #[doc = "< The shader stage to transpile the shader with."]
    pub shader_stage: SDL_ShaderCross_ShaderStage,
    #[doc = "< A properties ID for extensions. Should be 0 if no extensions are needed."]
    pub props: SDL_PropertiesID,
}
impl Default for SDL_ShaderCross_SPIRV_Info {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SDL_ShaderCross_HLSL_Define {
    #[doc = "< The define name."]
    pub name: *mut core::ffi::c_char,
    #[doc = "< An optional value for the define. Can be NULL."]
    pub value: *mut core::ffi::c_char,
}
impl Default for SDL_ShaderCross_HLSL_Define {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
pub struct SDL_ShaderCross_HLSL_Info {
    #[doc = "< The HLSL source code for the shader."]
    pub source: *const core::ffi::c_char,
    #[doc = "< The entry point function name for the shader in UTF-8."]
    pub entrypoint: *const core::ffi::c_char,
    #[doc = "< The include directory for shader code. Optional, can be NULL."]
    pub include_dir: *const core::ffi::c_char,
    #[doc = "< An array of defines. Optional, can be NULL. If not NULL, must be terminated with a fully NULL define struct."]
    pub defines: *mut SDL_ShaderCross_HLSL_Define,
    #[doc = "< The shader stage to compile the shader with."]
    pub shader_stage: SDL_ShaderCross_ShaderStage,
    #[doc = "< A properties ID for extensions. Should be 0 if no extensions are needed."]
    pub props: SDL_PropertiesID,
}
impl Default for SDL_ShaderCross_HLSL_Info {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    #[doc = " Initializes SDL_shadercross\n\n \\threadsafety This should only be called once, from a single thread.\n \\returns true on success, false otherwise."]
    pub fn SDL_ShaderCross_Init() -> bool;
}
unsafe extern "C" {
    #[doc = " De-initializes SDL_shadercross\n\n \\threadsafety This should only be called once, from a single thread."]
    pub fn SDL_ShaderCross_Quit();
}
unsafe extern "C" {
    #[doc = " Get the supported shader formats that SPIRV cross-compilation can output\n\n \\threadsafety It is safe to call this function from any thread.\n \\returns GPU shader formats supported by SPIRV cross-compilation."]
    pub fn SDL_ShaderCross_GetSPIRVShaderFormats() -> SDL_GPUShaderFormat;
}
unsafe extern "C" {
    #[doc = " Transpile to MSL code from SPIRV code.\n\n You must SDL_free the returned string once you are done with it.\n\n These are the optional properties that can be used:\n\n - `SDL_SHADERCROSS_PROP_SPIRV_MSL_VERSION_STRING`: specifies the MSL version that should be emitted. Defaults to 1.2.0.\n\n \\param info a struct describing the shader to transpile.\n \\returns an SDL_malloc'd string containing MSL code."]
    pub fn SDL_ShaderCross_TranspileMSLFromSPIRV(
        info: *const SDL_ShaderCross_SPIRV_Info,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Transpile to HLSL code from SPIRV code.\n\n You must SDL_free the returned string once you are done with it.\n\n These are the optional properties that can be used:\n\n - `SDL_SHADERCROSS_PROP_SPIRV_PSSL_COMPATIBILITY_BOOLEAN`: generates PSSL-compatible shader.\n\n \\param info a struct describing the shader to transpile.\n \\returns an SDL_malloc'd string containing HLSL code."]
    pub fn SDL_ShaderCross_TranspileHLSLFromSPIRV(
        info: *const SDL_ShaderCross_SPIRV_Info,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Compile DXBC bytecode from SPIRV code.\n\n You must SDL_free the returned buffer once you are done with it.\n\n \\param info a struct describing the shader to transpile.\n \\param size filled in with the bytecode buffer size.\n \\returns an SDL_malloc'd buffer containing DXBC bytecode."]
    pub fn SDL_ShaderCross_CompileDXBCFromSPIRV(
        info: *const SDL_ShaderCross_SPIRV_Info,
        size: *mut usize,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Compile DXIL bytecode from SPIRV code.\n\n You must SDL_free the returned buffer once you are done with it.\n\n \\param info a struct describing the shader to transpile.\n \\param size filled in with the bytecode buffer size.\n \\returns an SDL_malloc'd buffer containing DXIL bytecode."]
    pub fn SDL_ShaderCross_CompileDXILFromSPIRV(
        info: *const SDL_ShaderCross_SPIRV_Info,
        size: *mut usize,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Compile an SDL GPU shader from SPIRV code. If your shader source is HLSL, you should obtain SPIR-V bytecode from SDL_ShaderCross_CompileSPIRVFromHLSL().\n\n \\param device the SDL GPU device.\n \\param info a struct describing the shader to transpile.\n \\param resource_info a struct describing resource info of the shader. Can be obtained from SDL_ShaderCross_ReflectGraphicsSPIRV().\n \\param props a properties object filled in with extra shader metadata.\n \\returns a compiled SDL_GPUShader.\n\n \\threadsafety It is safe to call this function from any thread."]
    pub fn SDL_ShaderCross_CompileGraphicsShaderFromSPIRV(
        device: *mut SDL_GPUDevice,
        info: *const SDL_ShaderCross_SPIRV_Info,
        resource_info: *const SDL_ShaderCross_GraphicsShaderResourceInfo,
        props: SDL_PropertiesID,
    ) -> *mut SDL_GPUShader;
}
unsafe extern "C" {
    #[doc = " Compile an SDL GPU compute pipeline from SPIRV code. If your shader source is HLSL, you should obtain SPIR-V bytecode from SDL_ShaderCross_CompileSPIRVFromHLSL().\n\n \\param device the SDL GPU device.\n \\param info a struct describing the shader to transpile.\n \\param metadata a struct describing shader metadata. Can be obtained from SDL_ShaderCross_ReflectComputeSPIRV().\n \\param props a properties object filled in with extra shader metadata.\n \\returns a compiled SDL_GPUComputePipeline.\n\n \\threadsafety It is safe to call this function from any thread."]
    pub fn SDL_ShaderCross_CompileComputePipelineFromSPIRV(
        device: *mut SDL_GPUDevice,
        info: *const SDL_ShaderCross_SPIRV_Info,
        metadata: *const SDL_ShaderCross_ComputePipelineMetadata,
        props: SDL_PropertiesID,
    ) -> *mut SDL_GPUComputePipeline;
}
unsafe extern "C" {
    #[doc = " Reflect graphics shader info from SPIRV code. If your shader source is HLSL, you should obtain SPIR-V bytecode from SDL_ShaderCross_CompileSPIRVFromHLSL(). This must be freed with SDL_free() when you are done with the metadata.\n\n \\param bytecode the SPIRV bytecode.\n \\param bytecode_size the length of the SPIRV bytecode.\n \\param props a properties object filled in with extra shader metadata, provided by the user.\n \\returns A metadata struct on success, NULL otherwise. The struct must be free'd when it is no longer needed.\n\n \\threadsafety It is safe to call this function from any thread."]
    pub fn SDL_ShaderCross_ReflectGraphicsSPIRV(
        bytecode: *const Uint8,
        bytecode_size: usize,
        props: SDL_PropertiesID,
    ) -> *mut SDL_ShaderCross_GraphicsShaderMetadata;
}
unsafe extern "C" {
    #[doc = " Reflect compute pipeline info from SPIRV code. If your shader source is HLSL, you should obtain SPIR-V bytecode from SDL_ShaderCross_CompileSPIRVFromHLSL(). This must be freed with SDL_free() when you are done with the metadata.\n\n \\param bytecode the SPIRV bytecode.\n \\param bytecode_size the length of the SPIRV bytecode.\n \\param props a properties object filled in with extra shader metadata, provided by the user.\n \\returns A metadata struct on success, NULL otherwise.\n\n \\threadsafety It is safe to call this function from any thread."]
    pub fn SDL_ShaderCross_ReflectComputeSPIRV(
        bytecode: *const Uint8,
        bytecode_size: usize,
        props: SDL_PropertiesID,
    ) -> *mut SDL_ShaderCross_ComputePipelineMetadata;
}
unsafe extern "C" {
    #[doc = " Get the supported shader formats that HLSL cross-compilation can output\n\n \\returns GPU shader formats supported by HLSL cross-compilation.\n\n \\threadsafety It is safe to call this function from any thread."]
    pub fn SDL_ShaderCross_GetHLSLShaderFormats() -> SDL_GPUShaderFormat;
}
unsafe extern "C" {
    #[doc = " Compile to DXBC bytecode from HLSL code via a SPIRV-Cross round trip.\n\n You must SDL_free the returned buffer once you are done with it.\n\n These are the optional properties that can be used:\n\n - `SDL_SHADERCROSS_PROP_SHADER_DEBUG_ENABLE_BOOLEAN`: allows debug info to be emitted when relevant. Should only be used with debugging tools like Renderdoc.\n - `SDL_SHADERCROSS_PROP_SHADER_DEBUG_NAME_STRING`: a UTF-8 name to be used with the shader. Relevant for use with debugging tools like Renderdoc.\n - `SDL_SHADERCROSS_PROP_SHADER_CULL_UNUSED_BINDINGS_BOOLEAN`: When true, indicates that the compiler should cull unused shader resources. This behavior is disabled by default.\n - `SDL_SHADERCROSS_PROP_HLSL_SKIP_SPIRV_ROUNDTRIP_BOOLEAN`: When true, the SPIRV roundtrip is skipped. This behavior is disabled by default. Do not use this property if your shader uses Structured Buffers.\n\n \\param info a struct describing the shader to transpile.\n \\param size filled in with the bytecode buffer size.\n \\returns an SDL_malloc'd buffer containing DXBC bytecode.\n\n \\threadsafety It is safe to call this function from any thread."]
    pub fn SDL_ShaderCross_CompileDXBCFromHLSL(
        info: *const SDL_ShaderCross_HLSL_Info,
        size: *mut usize,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Compile to DXIL bytecode from HLSL code via a SPIRV-Cross round trip.\n\n You must SDL_free the returned buffer once you are done with it.\n\n These are the optional properties that can be used:\n\n - `SDL_SHADERCROSS_PROP_SHADER_DEBUG_ENABLE_BOOLEAN`: allows debug info to be emitted when relevant. Should only be used with debugging tools like Renderdoc.\n - `SDL_SHADERCROSS_PROP_SHADER_DEBUG_NAME_STRING`: a UTF-8 name to be used with the shader. Relevant for use with debugging tools like Renderdoc.\n - `SDL_SHADERCROSS_PROP_SHADER_CULL_UNUSED_BINDINGS_BOOLEAN`: when true, indicates that the compiler should cull unused shader resources. This behavior is disabled by default.\n - `SDL_SHADERCROSS_PROP_HLSL_SKIP_SPIRV_ROUNDTRIP_BOOLEAN`: when true, the SPIRV roundtrip is skipped. This behavior is disabled by default. Do not use this property if your shader uses Structured Buffers.\n\n \\param info a struct describing the shader to transpile.\n \\param size filled in with the bytecode buffer size.\n \\returns an SDL_malloc'd buffer containing DXIL bytecode.\n\n \\threadsafety It is safe to call this function from any thread."]
    pub fn SDL_ShaderCross_CompileDXILFromHLSL(
        info: *const SDL_ShaderCross_HLSL_Info,
        size: *mut usize,
    ) -> *mut core::ffi::c_void;
}
unsafe extern "C" {
    #[doc = " Compile to SPIRV bytecode from HLSL code.\n\n You must SDL_free the returned buffer once you are done with it.\n\n These are the optional properties that can be used:\n\n - `SDL_SHADERCROSS_PROP_SHADER_DEBUG_ENABLE_BOOLEAN`: allows debug info to be emitted when relevant. Should only be used with debugging tools like Renderdoc.\n - `SDL_SHADERCROSS_PROP_SHADER_DEBUG_NAME_STRING`: a UTF-8 name to be used with the shader. Relevant for use with debugging tools like Renderdoc.\n - `SDL_SHADERCROSS_PROP_SHADER_CULL_UNUSED_BINDINGS_BOOLEAN`: when true, indicates that the compiler should cull unused shader resources. This behavior is disabled by default.\n\n \\param info a struct describing the shader to transpile.\n \\param size filled in with the bytecode buffer size.\n \\returns an SDL_malloc'd buffer containing SPIRV bytecode.\n\n \\threadsafety It is safe to call this function from any thread."]
    pub fn SDL_ShaderCross_CompileSPIRVFromHLSL(
        info: *const SDL_ShaderCross_HLSL_Info,
        size: *mut usize,
    ) -> *mut core::ffi::c_void;
}
