//! Raw FFI bindings to SDL3.
//!
//! The contents are generated by bindgen from the vendored SDL headers and
//! committed to the repository; see `src/bin/regenerate.rs`.

#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::all)]

include!("bindings.rs");

extern crate alloc;

use core::error;
use core::ffi::CStr;
use core::fmt;

use alloc::string::String;

#[derive(Debug)]
pub struct SdlError(String);

impl SdlError {
    pub fn new<T>(desc: T) -> Self
    where
        T: Into<String>,
    {
        Self(desc.into())
    }
}

impl fmt::Display for SdlError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl error::Error for SdlError {
    fn description(&self) -> &str {
        &self.0
    }
}

pub fn get_error() -> SdlError {
    unsafe {
        SdlError(
            CStr::from_ptr(SDL_GetError())
                .to_string_lossy()
                .into_owned(),
        )
    }
}
