//! Raw FFI bindings to SDL3.
//!
//! The contents are generated by bindgen from the vendored SDL headers and
//! committed to the repository; see `src/bin/regenerate.rs`.

#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::all)]

include!("bindings.rs");
