[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
logging.workspace = true
math.workspace = true
sdl3.workspace = true
sdl3-image.workspace = true
utils.workspace = true
rquickjs = "0.12.2"
cosmic-text = { version = "0.19.0", default-features = false, features = ["std", "swash"] }
