[package]
name = "karna"
description = "!"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "karna"
path = "src/lib.rs"

[features]
default = ["build-from-source", "js", "lua"]
build-from-source = [
    "karna-engine/build-from-source",
    "karna-sdl3/build-from-source",
    "karna-js-scripting?/build-from-source",
    "karna-lua-scripting?/build-from-source",
]

js = ["dep:karna-js-scripting"]
lua = ["dep:karna-lua-scripting"]

[dependencies]
karna-engine.workspace = true
karna-math.workspace = true
karna-utils.workspace = true
karna-sdl3.workspace = true
karna-nostd.workspace = true
karna-js-scripting = { workspace = true, optional = true }
karna-lua-scripting = { workspace = true, optional = true }

[dev-dependencies]
traccia.workspace = true

[[example]]
name = "js"
required-features = ["js"]

[[example]]
name = "lua"
required-features = ["lua"]
