//! Raw FFI bindings to SDL3_shadercross.
//!
//! The contents are generated by bindgen from the vendored SDL_shadercross
//! headers and committed to the repository; see `src/bin/regenerate.rs`.
//!
//! Only `SDL_ShaderCross_*` items are generated here. SDL types they refer to
//! (`SDL_GPUDevice`, `SDL_GPUShader`, `SDL_GPUShaderFormat`, ...) come from
//! `sdl3_sys`, so values pass between the two crates without casts.

#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::all)]

use sdl3_sys::*;

include!("bindings.rs");
