[package]
name = "karna-math"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
karna-traits = { path = "../karna-traits" }
num = "0.4.3"

[dev-dependencies]
const-random = "0.1.18"
nalgebra = "0.33.2"

[lib]
doctest = false
